[package]
name = "torca-tor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
arti-client = { version = "0.45", default-features = false, features = ["experimental-api", "onion-service-client", "onion-service-service", "rustls", "static-sqlite", "tokio"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
safelog = "0.9"
tor-hsservice = "0.45"
tor-cell = "0.45"
tor-rtcompat = { version = "0.45", features = ["tokio", "rustls"] }
tor-proto = "0.45"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
torca-foundation = { path = "../../foundation/torca-foundation" }
torca-peer = { path = "../torca-peer" }
torca-runtime = { path = "../../application/torca-runtime" }
torca-peer-protocol = { path = "../../protocol/torca-peer-protocol" }
torca-transport-api = { path = "../../application/torca-transport-api" }
torca-wire = { path = "../../protocol/torca-wire" }

[lints]
workspace = true
