fn main() {
    println!("cargo:rerun-if-env-changed=TORCA_BUILD_ID");
    println!("cargo:rerun-if-env-changed=TORCA_PRODUCT_VERSION");
    println!("cargo:rerun-if-env-changed=TORCA_SOURCE_COMMIT");
    println!("cargo:rerun-if-env-changed=TORCA_SOURCE_FINGERPRINT");
    println!("cargo:rerun-if-env-changed=TORCA_PROVIDER_ENDPOINT");
    println!("cargo:rerun-if-env-changed=TORCA_PROVIDER_ENDPOINT_HASH");
    println!("cargo:rerun-if-env-changed=TORCA_IROH_PROFILE");
    println!("cargo:rerun-if-env-changed=TORCA_IROH_RELAY_URLS");
    println!("cargo:rerun-if-env-changed=TORCA_IROH_PKARR_URL");

    // The Iroh dependency owns its service configuration and embeds it from
    // its own build script. Native still embeds the profile because the
    // registry metadata is generated by this crate as well.
    if std::env::var_os("CARGO_FEATURE_PROVIDER_IROH").is_some()
        && let Ok(value) = std::env::var("TORCA_IROH_PROFILE")
        && !value.contains('\r')
        && !value.contains('\n')
    {
        println!("cargo:rustc-env=TORCA_IROH_PROFILE={value}");
    }
}
