//! A dependency-light policy kernel for demand-driven runtime work.
//!
//! The kernel deliberately does not own sockets, storage, Flutter, JNI or Tor.
//! Feature executors submit attention, demand and evidence events and receive
//! bounded permits from [`RuntimeGovernor`]. This keeps power policy reusable
//! across peer, relay, pairing, attachment and radio implementations.

use std::collections::{BTreeMap, HashMap, HashSet};
use std::sync::{Condvar, Mutex};
use std::time::{Duration, Instant};

use torca_foundation::OpaqueId;

const DEFAULT_LIVE_WINDOW: Duration = Duration::from_secs(15);
const DEFAULT_RECENT_WINDOW: Duration = Duration::from_secs(120);

/// A UI surface currently receiving user attention.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum AttentionSurface {
    Background,
    Home,
    Chats,
    Contacts,
    Conversation(OpaqueId),
    ConnectionDetails(OpaqueId),
    Pairing(OpaqueId),
    Radio(OpaqueId),
    Diagnostics,
}

/// Ephemeral UI context. It is never persisted or transmitted to a peer.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AttentionContext {
    pub surface: AttentionSurface,
    pub focused_resource: Option<OpaqueId>,
    pub visible_contact_ids: Vec<OpaqueId>,
    pub generation: u64,
}

impl Default for AttentionContext {
    fn default() -> Self {
        Self {
            surface: AttentionSurface::Background,
            focused_resource: None,
            visible_contact_ids: Vec::new(),
            generation: 0,
        }
    }
}

/// Durable or user-visible work that may justify a lease.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum DemandReason {
    VisibleConversation,
    VisibleContact,
    PendingMessage,
    AttachmentTransfer,
    ActivePairing,
    RadioSession,
    IncomingSession,
    RecentConversation,
    ExplicitDiagnostic,
    BackgroundRendezvous,
}

/// A resource controlled by policy. Feature crates map their own IDs here.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ResourceScope {
    Tor,
    Onion,
    Relay,
    Peer(OpaqueId),
    Delivery(OpaqueId),
    Pairing(OpaqueId),
    Attachment(OpaqueId),
    Radio(OpaqueId),
}

/// A class of work that can consume a scheduler/budget permit.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum WorkClass {
    TorWake,
    OnionPublish,
    RelayConnect,
    RelayProbe,
    PeerDial,
    PeerProbe,
    PairingPoll,
    Delivery,
    Attachment,
    Radio,
    Projection,
    Cleanup,
}

/// Health evidence generated by real traffic or an explicit probe.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EvidenceKind {
    Tx,
    Rx,
    Ack,
    Handshake,
    Probe,
    Failure,
}

/// How fresh the latest successful evidence is for a network generation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Freshness {
    Live,
    Recent,
    Stale,
    Unknown,
}

/// Mutable evidence for one resource, kept only in runtime memory.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct HealthEvidence {
    pub last_tx: Option<Instant>,
    pub last_rx: Option<Instant>,
    pub last_ack: Option<Instant>,
    pub last_handshake: Option<Instant>,
    pub last_probe: Option<Instant>,
    pub last_failure: Option<Instant>,
    pub network_generation: u64,
}

impl HealthEvidence {
    /// Returns the most recent successful activity timestamp.
    pub fn last_activity(&self) -> Option<Instant> {
        [self.last_tx, self.last_rx, self.last_ack, self.last_handshake].into_iter().flatten().max()
    }

    /// Classifies evidence without treating a stale network generation as live.
    pub fn freshness(&self, now: Instant, network_generation: u64) -> Freshness {
        if self.network_generation != network_generation {
            return if self.last_activity().is_some() {
                Freshness::Stale
            } else {
                Freshness::Unknown
            };
        }
        let Some(last) = self.last_activity() else { return Freshness::Unknown };
        let age = now.saturating_duration_since(last);
        if age <= DEFAULT_LIVE_WINDOW {
            Freshness::Live
        } else if age <= DEFAULT_RECENT_WINDOW {
            Freshness::Recent
        } else {
            Freshness::Stale
        }
    }
}

/// A temporary permission to keep one resource active.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ConnectionLease {
    pub scope: ResourceScope,
    pub reason: DemandReason,
    pub owner: OpaqueId,
    pub expires_at: Instant,
}

impl ConnectionLease {
    /// Whether the lease is still valid at `now`.
    pub fn active_at(&self, now: Instant) -> bool {
        self.expires_at > now
    }
}

/// A scheduled work permit returned by the governor.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WorkPermit {
    pub scope: ResourceScope,
    pub class: WorkClass,
    pub due_at: Instant,
    pub cost: u32,
}

/// A work request supplied to the scheduler.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WorkDemand {
    pub scope: ResourceScope,
    pub class: WorkClass,
    pub reason: DemandReason,
    pub owner: OpaqueId,
    pub expires_at: Instant,
}

/// Events accepted by the policy reducer.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum PolicyEvent {
    Attention(AttentionContext),
    NetworkChanged { generation: u64 },
    Evidence { scope: ResourceScope, kind: EvidenceKind },
    Demand(WorkDemand),
    Release { owner: OpaqueId },
}

/// Changes produced by applying one policy event.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct PolicyDelta {
    pub attention_changed: bool,
    pub network_changed: bool,
    pub permits_due: Vec<WorkPermit>,
}

#[derive(Clone, Copy, Debug)]
struct TokenBucket {
    capacity: u32,
    tokens: u32,
    refill_every: Duration,
    last_refill: Instant,
}

impl TokenBucket {
    fn new(now: Instant, capacity: u32, refill_every: Duration) -> Self {
        Self { capacity, tokens: capacity, refill_every, last_refill: now }
    }

    fn consume(&mut self, now: Instant, cost: u32) -> bool {
        let elapsed = now.saturating_duration_since(self.last_refill);
        if elapsed >= self.refill_every {
            let units = elapsed.as_nanos() / self.refill_every.as_nanos().max(1);
            let refill = u32::try_from(units).unwrap_or(u32::MAX);
            self.tokens = self.tokens.saturating_add(refill).min(self.capacity);
            self.last_refill = now;
        }
        if self.tokens < cost {
            return false;
        }
        self.tokens -= cost;
        true
    }
}

/// Cheap runtime counters used by diagnostics and idle regression tests.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RuntimeStats {
    pub scheduler_wakeups: u64,
    pub permits_issued: u64,
    pub evidence_events: u64,
    pub peer_probes: u64,
    pub relay_probes: u64,
    pub snapshot_builds: u64,
}

/// A synchronous, deterministic policy kernel shared by feature executors.
pub struct RuntimeGovernor {
    attention: AttentionContext,
    network_generation: u64,
    leases: HashMap<OpaqueId, ConnectionLease>,
    demands: HashMap<OpaqueId, WorkDemand>,
    evidence: HashMap<ResourceScope, HealthEvidence>,
    deadlines: BTreeMap<Instant, Vec<WorkPermit>>,
    budgets: HashMap<WorkClass, TokenBucket>,
    stats: RuntimeStats,
}

impl RuntimeGovernor {
    /// Creates an idle governor with no scheduled work.
    pub fn new(now: Instant) -> Self {
        Self {
            attention: AttentionContext::default(),
            network_generation: 0,
            leases: HashMap::new(),
            demands: HashMap::new(),
            evidence: HashMap::new(),
            deadlines: BTreeMap::new(),
            budgets: default_budgets(now),
            stats: RuntimeStats::default(),
        }
    }

    /// Applies one event and returns permits that are immediately due.
    pub fn apply(&mut self, event: PolicyEvent, now: Instant) -> PolicyDelta {
        let mut delta = PolicyDelta::default();
        match event {
            PolicyEvent::Attention(context) if context.generation >= self.attention.generation => {
                delta.attention_changed = context != self.attention;
                self.attention = context;
            }
            PolicyEvent::Attention(_) => {}
            PolicyEvent::NetworkChanged { generation } if generation > self.network_generation => {
                self.network_generation = generation;
                for item in self.evidence.values_mut() {
                    item.network_generation = generation.saturating_sub(1);
                }
                delta.network_changed = true;
            }
            PolicyEvent::NetworkChanged { .. } => {}
            PolicyEvent::Evidence { scope, kind } => self.record_evidence(scope, kind, now),
            PolicyEvent::Demand(demand) => {
                let lease = ConnectionLease {
                    scope: demand.scope,
                    reason: demand.reason,
                    owner: demand.owner,
                    expires_at: demand.expires_at,
                };
                self.leases.insert(demand.owner, lease);
                self.demands.insert(demand.owner, demand);
            }
            PolicyEvent::Release { owner } => {
                self.leases.remove(&owner);
                self.demands.remove(&owner);
            }
        }
        delta.permits_due = self.take_due(now);
        delta
    }

    /// Acquires or replaces a lease for a demand owner.
    pub fn acquire_lease(&mut self, demand: WorkDemand) -> ConnectionLease {
        let lease = ConnectionLease {
            scope: demand.scope,
            reason: demand.reason,
            owner: demand.owner,
            expires_at: demand.expires_at,
        };
        self.leases.insert(demand.owner, lease);
        self.demands.insert(demand.owner, demand);
        lease
    }

    /// Releases a lease and its associated demand.
    pub fn release_lease(&mut self, owner: OpaqueId) {
        self.leases.remove(&owner);
        self.demands.remove(&owner);
    }

    /// Returns whether a scope has an unexpired lease.
    pub fn has_active_lease(&mut self, scope: ResourceScope, now: Instant) -> bool {
        self.expire(now);
        self.leases.values().any(|lease| lease.scope == scope && lease.active_at(now))
    }

    /// Records health evidence generated by actual feature activity.
    pub fn record_evidence(&mut self, scope: ResourceScope, kind: EvidenceKind, now: Instant) {
        let entry = self.evidence.entry(scope).or_default();
        entry.network_generation = self.network_generation;
        match kind {
            EvidenceKind::Tx => entry.last_tx = Some(now),
            EvidenceKind::Rx => entry.last_rx = Some(now),
            EvidenceKind::Ack => entry.last_ack = Some(now),
            EvidenceKind::Handshake => entry.last_handshake = Some(now),
            EvidenceKind::Probe => entry.last_probe = Some(now),
            EvidenceKind::Failure => entry.last_failure = Some(now),
        }
        self.stats.evidence_events = self.stats.evidence_events.saturating_add(1);
    }

    /// Returns freshness for a scope in the current network generation.
    pub fn freshness(&self, scope: ResourceScope, now: Instant) -> Freshness {
        self.evidence
            .get(&scope)
            .map_or(Freshness::Unknown, |item| item.freshness(now, self.network_generation))
    }

    /// Schedules a permit for a later deadline.
    pub fn schedule(&mut self, permit: WorkPermit) {
        self.deadlines.entry(permit.due_at).or_default().push(permit);
    }

    /// Returns the next scheduled wakeup, if any.
    pub fn next_deadline(&self) -> Option<Instant> {
        self.deadlines.keys().next().copied()
    }

    /// Takes due permits, applying the per-class budget and active-lease rule.
    pub fn take_due(&mut self, now: Instant) -> Vec<WorkPermit> {
        self.expire(now);
        let due_keys = self.deadlines.range(..=now).map(|(key, _)| *key).collect::<Vec<_>>();
        let mut permits = Vec::new();
        for key in due_keys {
            let Some(items) = self.deadlines.remove(&key) else { continue };
            for permit in items {
                if !self.has_active_lease(permit.scope, now) {
                    continue;
                }
                let budget = self
                    .budgets
                    .entry(permit.class)
                    .or_insert_with(|| TokenBucket::new(now, 2, Duration::from_secs(3)));
                if budget.consume(now, permit.cost.max(1)) {
                    if permit.class == WorkClass::PeerProbe {
                        self.stats.peer_probes = self.stats.peer_probes.saturating_add(1);
                    }
                    if permit.class == WorkClass::RelayProbe {
                        self.stats.relay_probes = self.stats.relay_probes.saturating_add(1);
                    }
                    self.stats.permits_issued = self.stats.permits_issued.saturating_add(1);
                    permits.push(permit);
                }
            }
        }
        if !permits.is_empty() {
            self.stats.scheduler_wakeups = self.stats.scheduler_wakeups.saturating_add(1);
        }
        permits
    }

    /// Returns a snapshot suitable for diagnostics and tests.
    pub fn snapshot(&mut self, now: Instant) -> RuntimePolicySnapshot {
        self.expire(now);
        RuntimePolicySnapshot {
            attention: self.attention.clone(),
            network_generation: self.network_generation,
            active_leases: self.leases.len(),
            active_demands: self.demands.len(),
            scheduled_deadlines: self.deadlines.len(),
            stats: self.stats,
        }
    }

    fn expire(&mut self, now: Instant) {
        self.leases.retain(|owner, lease| {
            let active = lease.active_at(now);
            if !active {
                self.demands.remove(owner);
            }
            active
        });
    }
}

/// Immutable diagnostic projection of the governor.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RuntimePolicySnapshot {
    pub attention: AttentionContext,
    pub network_generation: u64,
    pub active_leases: usize,
    pub active_demands: usize,
    pub scheduled_deadlines: usize,
    pub stats: RuntimeStats,
}

fn default_budgets(now: Instant) -> HashMap<WorkClass, TokenBucket> {
    let mut budgets = HashMap::new();
    for class in [WorkClass::PeerProbe, WorkClass::RelayProbe] {
        budgets.insert(class, TokenBucket::new(now, 2, Duration::from_secs(3)));
    }
    budgets
}

/// A process-local revision hub for replacing timer-driven polling.
pub struct RuntimeEventHub {
    state: Mutex<HubState>,
    changed: Condvar,
}

#[derive(Default)]
struct HubState {
    revision: u64,
    cursor: u64,
    cancelled: HashSet<u64>,
}

impl Default for RuntimeEventHub {
    fn default() -> Self {
        Self { state: Mutex::new(HubState::default()), changed: Condvar::new() }
    }
}

impl RuntimeEventHub {
    /// Publishes a new runtime revision and optional event cursor.
    pub fn publish(&self, cursor: u64) {
        if let Ok(mut state) = self.state.lock() {
            if cursor > state.cursor {
                state.revision = state.revision.saturating_add(1);
                state.cursor = cursor;
                self.changed.notify_all();
            }
        }
    }

    /// Waits until revision/cursor changes or timeout expires.
    pub fn wait(
        &self,
        waiter: u64,
        after_revision: u64,
        after_cursor: u64,
        timeout: Duration,
    ) -> Option<(u64, u64)> {
        let state = self.state.lock().ok()?;
        let ready = |state: &HubState| {
            state.revision > after_revision
                || state.cursor > after_cursor
                || state.cancelled.contains(&waiter)
        };
        let (state, _) =
            self.changed.wait_timeout_while(state, timeout, |state| !ready(state)).ok()?;
        if state.cancelled.contains(&waiter) {
            return None;
        }
        if ready(&state) { Some((state.revision, state.cursor)) } else { None }
    }

    /// Cancels a waiter token. Existing waits are woken by publishing.
    pub fn cancel(&self, waiter: u64) {
        if let Ok(mut state) = self.state.lock() {
            state.cancelled.insert(waiter);
            self.changed.notify_all();
        }
    }

    /// Returns current revision and cursor without waiting.
    pub fn current(&self) -> Option<(u64, u64)> {
        self.state.lock().ok().map(|state| (state.revision, state.cursor))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn id(value: u128) -> OpaqueId {
        OpaqueId::from_u128(value)
    }

    #[test]
    fn stale_attention_cannot_clear_newer_route() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        let newer = AttentionContext {
            surface: AttentionSurface::Conversation(id(2)),
            focused_resource: Some(id(2)),
            visible_contact_ids: vec![id(2)],
            generation: 2,
        };
        governor.apply(PolicyEvent::Attention(newer.clone()), now);
        let stale = AttentionContext { generation: 1, ..AttentionContext::default() };
        governor.apply(PolicyEvent::Attention(stale), now);
        assert_eq!(governor.snapshot(now).attention, newer);
    }

    #[test]
    fn real_activity_makes_probe_unnecessary_until_stale() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        let scope = ResourceScope::Peer(id(3));
        governor.record_evidence(scope, EvidenceKind::Rx, now);
        assert_eq!(governor.freshness(scope, now + Duration::from_secs(10)), Freshness::Live);
        assert_eq!(governor.freshness(scope, now + Duration::from_secs(121)), Freshness::Stale);
    }

    #[test]
    fn permits_require_active_lease_and_consume_budget() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        let owner = id(4);
        let scope = ResourceScope::Peer(id(5));
        governor.acquire_lease(WorkDemand {
            scope,
            class: WorkClass::PeerProbe,
            reason: DemandReason::VisibleConversation,
            owner,
            expires_at: now + Duration::from_secs(10),
        });
        governor.schedule(WorkPermit { scope, class: WorkClass::PeerProbe, due_at: now, cost: 1 });
        assert_eq!(governor.take_due(now).len(), 1);
        governor.release_lease(owner);
        governor.schedule(WorkPermit { scope, class: WorkClass::PeerProbe, due_at: now, cost: 1 });
        assert!(governor.take_due(now).is_empty());
    }

    #[test]
    fn event_hub_sleeps_until_publish() {
        let hub = RuntimeEventHub::default();
        assert_eq!(hub.current(), Some((0, 0)));
        hub.publish(7);
        assert_eq!(hub.wait(1, 0, 0, Duration::ZERO), Some((1, 7)));
    }

    #[test]
    fn event_hub_cancellation_does_not_look_like_a_runtime_change() {
        let hub = RuntimeEventHub::default();
        hub.cancel(9);
        assert_eq!(hub.wait(9, 0, 0, Duration::ZERO), None);
        assert_eq!(hub.current(), Some((0, 0)));
    }
}
