//! A dependency-light policy kernel for demand-driven runtime work.
//!
//! The kernel deliberately does not own sockets, storage, Flutter, JNI or Tor.
//! Feature executors submit attention, demand and evidence events and receive
//! bounded permits from [`RuntimeGovernor`]. This keeps power policy reusable
//! across peer, relay, pairing, attachment and radio implementations.

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::sync::{Condvar, Mutex};
use std::time::{Duration, Instant};

use torca_foundation::OpaqueId;

const DEFAULT_LIVE_WINDOW: Duration = Duration::from_secs(15);
const DEFAULT_RECENT_WINDOW: Duration = Duration::from_secs(120);

/// A UI surface currently receiving user attention.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum AttentionSurface {
    Background,
    Home,
    Chats,
    Contacts,
    Conversation(OpaqueId),
    ConnectionDetails(OpaqueId),
    Pairing(OpaqueId),
    Radio(OpaqueId),
    Diagnostics,
}

/// Ephemeral UI context. It is never persisted or transmitted to a peer.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AttentionContext {
    pub surface: AttentionSurface,
    pub focused_resource: Option<OpaqueId>,
    pub visible_contact_ids: Vec<OpaqueId>,
    pub generation: u64,
}

impl Default for AttentionContext {
    fn default() -> Self {
        Self {
            surface: AttentionSurface::Background,
            focused_resource: None,
            visible_contact_ids: Vec::new(),
            generation: 0,
        }
    }
}

/// Durable or user-visible work that may justify a lease.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum DemandReason {
    BootstrapValidation,
    VisibleConversation,
    VisibleContact,
    PendingMessage,
    AttachmentTransfer,
    ActivePairing,
    RadioSession,
    IncomingSession,
    RecentConversation,
    ExplicitDiagnostic,
    InstantContact,
    /// Explicit, time-boxed user boost for one conversation.
    FocusedConversation,
}

/// A resource controlled by policy. Feature crates map their own IDs here.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ResourceScope {
    Tor,
    Onion,
    Relay,
    Peer(OpaqueId),
    Delivery(OpaqueId),
    Pairing(OpaqueId),
    Attachment(OpaqueId),
    Radio(OpaqueId),
}

/// A class of work that can consume a scheduler/budget permit.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum WorkClass {
    TorWake,
    OnionPublish,
    RelayConnect,
    RelayProbe,
    PeerDial,
    PeerProbe,
    PairingPoll,
    Delivery,
    Attachment,
    Radio,
    Projection,
    Cleanup,
}

/// Health evidence generated by real traffic or an explicit probe.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EvidenceKind {
    Tx,
    Rx,
    Ack,
    Handshake,
    Probe,
    Failure,
}

/// How fresh the latest successful evidence is for a network generation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Freshness {
    Live,
    Recent,
    Stale,
    Unknown,
}

/// Mutable evidence for one resource, kept only in runtime memory.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct HealthEvidence {
    pub last_tx: Option<Instant>,
    pub last_rx: Option<Instant>,
    pub last_ack: Option<Instant>,
    pub last_handshake: Option<Instant>,
    pub last_probe: Option<Instant>,
    pub last_failure: Option<Instant>,
    pub network_generation: u64,
}

impl HealthEvidence {
    /// Returns the most recent successful activity timestamp.
    pub fn last_activity(&self) -> Option<Instant> {
        [self.last_tx, self.last_rx, self.last_ack, self.last_handshake].into_iter().flatten().max()
    }

    /// Classifies evidence without treating a stale network generation as live.
    pub fn freshness(&self, now: Instant, network_generation: u64) -> Freshness {
        if self.network_generation != network_generation {
            return if self.last_activity().is_some() {
                Freshness::Stale
            } else {
                Freshness::Unknown
            };
        }
        let Some(last) = self.last_activity() else { return Freshness::Unknown };
        let age = now.saturating_duration_since(last);
        if age <= DEFAULT_LIVE_WINDOW {
            Freshness::Live
        } else if age <= DEFAULT_RECENT_WINDOW {
            Freshness::Recent
        } else {
            Freshness::Stale
        }
    }
}

/// A temporary permission to keep one resource active.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ConnectionLease {
    pub scope: ResourceScope,
    pub reason: DemandReason,
    pub owner: OpaqueId,
    pub lifetime: LeaseLifetime,
}

/// Explicit ownership semantics for runtime demand.
///
/// UI attention and durable jobs use `UntilRelease`; bounded retries and
/// protocol expiry use `Until`. This removes the old side-table that inferred
/// persistence from the owner ID.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LeaseLifetime {
    Until(Instant),
    UntilRelease,
}

impl LeaseLifetime {
    fn active_at(self, now: Instant) -> bool {
        match self {
            Self::Until(expires_at) => expires_at > now,
            Self::UntilRelease => true,
        }
    }

    fn expiry(self) -> Option<Instant> {
        match self {
            Self::Until(expires_at) => Some(expires_at),
            Self::UntilRelease => None,
        }
    }
}

/// A user-visible, time-boxed priority lease. There is at most one active
/// focus lease in a governor.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FocusLease {
    pub contact: OpaqueId,
    pub owner: OpaqueId,
    pub expires_at: Instant,
}

impl FocusLease {
    pub fn active_at(self, now: Instant) -> bool {
        self.expires_at > now
    }
}

impl ConnectionLease {
    /// Whether the lease is still valid at `now`.
    pub fn active_at(&self, now: Instant) -> bool {
        self.lifetime.active_at(now)
    }
}

/// A work request supplied to the scheduler.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WorkDemand {
    pub scope: ResourceScope,
    pub class: WorkClass,
    pub reason: DemandReason,
    pub owner: OpaqueId,
    pub expires_at: Instant,
}

/// Events accepted by the policy reducer.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum PolicyEvent {
    Attention(AttentionContext),
    NetworkChanged { generation: u64 },
    Evidence { scope: ResourceScope, kind: EvidenceKind },
    Demand(WorkDemand),
    Release { owner: OpaqueId },
}

/// Changes produced by applying one policy event.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct PolicyDelta {
    pub attention_changed: bool,
    pub network_changed: bool,
}

/// Cheap runtime counters used by diagnostics and idle regression tests.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RuntimeStats {
    pub evidence_events: u64,
    pub snapshot_builds: u64,
}

/// A synchronous, deterministic policy kernel shared by feature executors.
pub struct RuntimeGovernor {
    attention: AttentionContext,
    network_generation: u64,
    leases: HashMap<OpaqueId, ConnectionLease>,
    focus: Option<FocusLease>,
    demands: HashMap<OpaqueId, WorkDemand>,
    evidence: HashMap<ResourceScope, HealthEvidence>,
    stats: RuntimeStats,
}

impl RuntimeGovernor {
    /// Creates an idle governor with no scheduled work.
    pub fn new(_now: Instant) -> Self {
        Self {
            attention: AttentionContext::default(),
            network_generation: 0,
            leases: HashMap::new(),
            focus: None,
            demands: HashMap::new(),
            evidence: HashMap::new(),
            stats: RuntimeStats::default(),
        }
    }

    /// Applies one event and returns permits that are immediately due.
    pub fn apply(&mut self, event: PolicyEvent, now: Instant) -> PolicyDelta {
        let mut delta = PolicyDelta::default();
        match event {
            PolicyEvent::Attention(context) if context.generation >= self.attention.generation => {
                delta.attention_changed = context != self.attention;
                self.attention = context;
            }
            PolicyEvent::Attention(_) => {}
            PolicyEvent::NetworkChanged { generation } if generation > self.network_generation => {
                self.network_generation = generation;
                for item in self.evidence.values_mut() {
                    item.network_generation = generation.saturating_sub(1);
                }
                delta.network_changed = true;
            }
            PolicyEvent::NetworkChanged { .. } => {}
            PolicyEvent::Evidence { scope, kind } => self.record_evidence(scope, kind, now),
            PolicyEvent::Demand(demand) => {
                let lease = ConnectionLease {
                    scope: demand.scope,
                    reason: demand.reason,
                    owner: demand.owner,
                    lifetime: LeaseLifetime::Until(demand.expires_at),
                };
                self.leases.insert(demand.owner, lease);
                self.demands.insert(demand.owner, demand);
            }
            PolicyEvent::Release { owner } => {
                self.leases.remove(&owner);
                self.demands.remove(&owner);
            }
        }
        delta
    }

    /// Acquires or replaces a lease for a demand owner.
    pub fn acquire_lease(&mut self, demand: WorkDemand) -> ConnectionLease {
        let lease = ConnectionLease {
            scope: demand.scope,
            reason: demand.reason,
            owner: demand.owner,
            lifetime: LeaseLifetime::Until(demand.expires_at),
        };
        self.leases.insert(demand.owner, lease);
        self.demands.insert(demand.owner, demand);
        lease
    }

    /// Acquires a lease that remains active until explicitly released.
    /// Persistent leases model user-selected Instant contacts and active
    /// radio sessions without manufacturing periodic renewal wakeups.
    pub fn acquire_persistent_lease(&mut self, demand: WorkDemand) -> ConnectionLease {
        let lease = ConnectionLease {
            scope: demand.scope,
            reason: demand.reason,
            owner: demand.owner,
            lifetime: LeaseLifetime::UntilRelease,
        };
        self.leases.insert(demand.owner, lease);
        self.demands.insert(demand.owner, demand);
        lease
    }

    /// Releases a lease and its associated demand.
    pub fn release_lease(&mut self, owner: OpaqueId) {
        self.leases.remove(&owner);
        self.demands.remove(&owner);
        if self.focus.is_some_and(|focus| focus.owner == owner) {
            self.focus = None;
        }
    }

    /// Installs the single explicit focus lease. Replacing a focus atomically
    /// removes the previous contact's demand before installing the new one.
    pub fn acquire_focus(
        &mut self,
        contact: OpaqueId,
        owner: OpaqueId,
        expires_at: Instant,
        now: Instant,
    ) -> FocusLease {
        if let Some(previous) = self.focus.take() {
            self.leases.remove(&previous.owner);
            self.demands.remove(&previous.owner);
        }
        let focus = FocusLease { contact, owner, expires_at };
        self.focus = Some(focus);
        self.acquire_lease(WorkDemand {
            scope: ResourceScope::Peer(contact),
            class: WorkClass::PeerDial,
            reason: DemandReason::FocusedConversation,
            owner,
            expires_at,
        });
        self.expire(now);
        focus
    }

    /// Installs UI focus that remains valid until the host explicitly changes
    /// attention or backgrounds.  It intentionally creates no renewal timer.
    pub fn acquire_persistent_focus(
        &mut self,
        contact: OpaqueId,
        owner: OpaqueId,
        now: Instant,
    ) -> FocusLease {
        if let Some(previous) = self.focus.take() {
            self.release_lease(previous.owner);
        }
        let focus = FocusLease { contact, owner, expires_at: now };
        self.focus = Some(focus);
        self.acquire_persistent_lease(WorkDemand {
            scope: ResourceScope::Peer(contact),
            class: WorkClass::PeerDial,
            reason: DemandReason::FocusedConversation,
            owner,
            expires_at: now,
        });
        focus
    }

    pub fn focus(&mut self, now: Instant) -> Option<FocusLease> {
        self.expire(now);
        self.focus
            .filter(|focus| self.leases.get(&focus.owner).is_some_and(|lease| lease.active_at(now)))
    }

    pub fn is_focused(&mut self, contact: OpaqueId, now: Instant) -> bool {
        self.focus(now).is_some_and(|focus| focus.contact == contact)
    }

    /// Returns whether a scope has an unexpired lease.
    pub fn has_active_lease(&mut self, scope: ResourceScope, now: Instant) -> bool {
        self.expire(now);
        self.leases.values().any(|lease| lease.scope == scope && lease.active_at(now))
    }

    /// Returns whether any feature currently owns work that must keep the
    /// network active. This is intentionally broader than a scope query and
    /// is used only for global Tor dormancy decisions.
    pub fn has_any_active_lease(&mut self, now: Instant) -> bool {
        self.expire(now);
        self.leases.values().any(|lease| lease.active_at(now))
    }

    /// Returns whether a lease represents work that must keep the transport
    /// awake. Cosmetic/viewport leases deliberately do not count: they may
    /// refresh while the app is visible, but they must never prevent Tor
    /// dormancy or force a reconnect storm.
    pub fn has_durable_lease(&mut self, now: Instant) -> bool {
        self.expire(now);
        self.leases.values().any(|lease| {
            let active = lease.active_at(now);
            active
                && matches!(
                    lease.reason,
                    DemandReason::BootstrapValidation
                        | DemandReason::PendingMessage
                        | DemandReason::AttachmentTransfer
                        | DemandReason::ActivePairing
                        | DemandReason::RadioSession
                        | DemandReason::IncomingSession
                        | DemandReason::InstantContact
                        | DemandReason::ExplicitDiagnostic
                )
        })
    }

    /// Returns only peers that currently own active runtime work.
    ///
    /// Known contacts deliberately do not appear here.  RuntimeOwner uses
    /// this set to reconcile live peer state without scanning an address book
    /// after an unrelated scheduler wake.
    pub fn active_peer_ids(&mut self, now: Instant) -> BTreeSet<OpaqueId> {
        self.expire(now);
        self.leases
            .values()
            .filter(|lease| lease.active_at(now))
            .filter_map(|lease| match lease.scope {
                ResourceScope::Peer(peer) | ResourceScope::Radio(peer) => Some(peer),
                _ => None,
            })
            .collect()
    }

    /// Records health evidence generated by actual feature activity.
    pub fn record_evidence(&mut self, scope: ResourceScope, kind: EvidenceKind, now: Instant) {
        let entry = self.evidence.entry(scope).or_default();
        entry.network_generation = self.network_generation;
        match kind {
            EvidenceKind::Tx => entry.last_tx = Some(now),
            EvidenceKind::Rx => entry.last_rx = Some(now),
            EvidenceKind::Ack => entry.last_ack = Some(now),
            EvidenceKind::Handshake => entry.last_handshake = Some(now),
            EvidenceKind::Probe => entry.last_probe = Some(now),
            EvidenceKind::Failure => entry.last_failure = Some(now),
        }
        self.stats.evidence_events = self.stats.evidence_events.saturating_add(1);
    }

    /// Returns freshness for a scope in the current network generation.
    pub fn freshness(&self, scope: ResourceScope, now: Instant) -> Freshness {
        self.evidence
            .get(&scope)
            .map_or(Freshness::Unknown, |item| item.freshness(now, self.network_generation))
    }

    /// Returns the earliest lease expiry so the host scheduler can retire
    /// demand without relying on a periodic maintenance tick.
    pub fn next_lease_expiry(&self) -> Option<Instant> {
        self.leases.values().filter_map(|lease| lease.lifetime.expiry()).min()
    }

    /// Returns a snapshot suitable for diagnostics and tests.
    pub fn snapshot(&mut self, now: Instant) -> RuntimePolicySnapshot {
        self.expire(now);
        let mut lease_reasons = BTreeMap::new();
        for lease in self.leases.values() {
            *lease_reasons.entry(lease.reason).or_insert(0_usize) += 1;
        }
        RuntimePolicySnapshot {
            attention: self.attention.clone(),
            network_generation: self.network_generation,
            active_leases: self.leases.len(),
            active_demands: self.demands.len(),
            // RuntimeOwner owns the only deadline registry. The governor is
            // policy state only: attention, leases and evidence.
            scheduled_deadlines: 0,
            active_lease_reasons: lease_reasons,
            scheduled_work_classes: BTreeMap::new(),
            next_deadline_in_ms: None,
            stats: self.stats,
            focus_active: self.focus.is_some(),
            focus_remaining_ms: self.focus.and_then(|focus| {
                self.leases.get(&focus.owner).and_then(|lease| match lease.lifetime {
                    LeaseLifetime::Until(expires_at) => Some(
                        expires_at
                            .saturating_duration_since(now)
                            .as_millis()
                            .min(u128::from(u64::MAX)) as u64,
                    ),
                    LeaseLifetime::UntilRelease => None,
                })
            }),
        }
    }

    fn expire(&mut self, now: Instant) {
        self.leases.retain(|owner, lease| {
            let active = lease.active_at(now);
            if !active {
                self.demands.remove(owner);
            }
            active
        });
        if self
            .focus
            .is_some_and(|focus| !self.leases.contains_key(&focus.owner) && !focus.active_at(now))
        {
            self.focus = None;
        }
    }
}

/// Immutable diagnostic projection of the governor.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RuntimePolicySnapshot {
    pub attention: AttentionContext,
    pub network_generation: u64,
    pub active_leases: usize,
    pub active_demands: usize,
    pub scheduled_deadlines: usize,
    /// Aggregated reasons are intentionally exported without resource IDs.
    /// This makes diagnostics useful while avoiding contact or relationship data.
    pub active_lease_reasons: BTreeMap<DemandReason, usize>,
    pub scheduled_work_classes: BTreeMap<WorkClass, usize>,
    pub next_deadline_in_ms: Option<u64>,
    pub stats: RuntimeStats,
    pub focus_active: bool,
    pub focus_remaining_ms: Option<u64>,
}

/// A process-local revision hub for replacing timer-driven polling.
pub struct RuntimeEventHub {
    state: Mutex<HubState>,
    changed: Condvar,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RuntimeEventHubStats {
    pub waits: u64,
    pub wakeups: u64,
    pub timeouts: u64,
    pub cancellations: u64,
}

#[derive(Default)]
struct HubState {
    revision: u64,
    cursor: u64,
    cancelled: HashSet<u64>,
    stats: RuntimeEventHubStats,
}

impl Default for RuntimeEventHub {
    fn default() -> Self {
        Self { state: Mutex::new(HubState::default()), changed: Condvar::new() }
    }
}

impl RuntimeEventHub {
    /// Publishes a new runtime revision and optional event cursor.
    pub fn publish(&self, cursor: u64) {
        if let Ok(mut state) = self.state.lock() {
            if cursor > state.cursor {
                state.revision = state.revision.saturating_add(1);
                state.cursor = cursor;
                self.changed.notify_all();
            }
        }
    }

    /// Waits until revision/cursor changes or timeout expires.
    pub fn wait(
        &self,
        waiter: u64,
        after_revision: u64,
        after_cursor: u64,
        timeout: Duration,
    ) -> Option<(u64, u64)> {
        let mut state = self.state.lock().ok()?;
        state.stats.waits = state.stats.waits.saturating_add(1);
        let ready = |state: &HubState| {
            state.revision > after_revision
                || state.cursor > after_cursor
                || state.cancelled.contains(&waiter)
        };
        let (mut state, _) =
            self.changed.wait_timeout_while(state, timeout, |state| !ready(state)).ok()?;
        if state.cancelled.remove(&waiter) {
            state.stats.cancellations = state.stats.cancellations.saturating_add(1);
            return None;
        }
        if ready(&state) {
            state.stats.wakeups = state.stats.wakeups.saturating_add(1);
            Some((state.revision, state.cursor))
        } else {
            state.stats.timeouts = state.stats.timeouts.saturating_add(1);
            None
        }
    }

    /// Waits without a timeout until a revision/cursor change or cancellation.
    /// Cancellation is one-shot so a worker can be stopped and later started
    /// again with the same runtime event hub.
    pub fn wait_indefinitely(
        &self,
        waiter: u64,
        after_revision: u64,
        after_cursor: u64,
    ) -> Option<(u64, u64)> {
        let mut state = self.state.lock().ok()?;
        state.stats.waits = state.stats.waits.saturating_add(1);
        let ready = |state: &HubState| {
            state.revision > after_revision
                || state.cursor > after_cursor
                || state.cancelled.contains(&waiter)
        };
        while !ready(&state) {
            state = self.changed.wait(state).ok()?;
        }
        if state.cancelled.remove(&waiter) {
            state.stats.cancellations = state.stats.cancellations.saturating_add(1);
            return None;
        }
        state.stats.wakeups = state.stats.wakeups.saturating_add(1);
        Some((state.revision, state.cursor))
    }

    /// Cancels a waiter token. Existing waits are woken by publishing.
    pub fn cancel(&self, waiter: u64) {
        if let Ok(mut state) = self.state.lock() {
            state.cancelled.insert(waiter);
            self.changed.notify_all();
        }
    }

    /// Returns current revision and cursor without waiting.
    pub fn current(&self) -> Option<(u64, u64)> {
        self.state.lock().ok().map(|state| (state.revision, state.cursor))
    }

    pub fn stats(&self) -> Option<RuntimeEventHubStats> {
        self.state.lock().ok().map(|state| state.stats)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn id(value: u128) -> OpaqueId {
        OpaqueId::from_u128(value)
    }

    #[test]
    fn stale_attention_cannot_clear_newer_route() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        let newer = AttentionContext {
            surface: AttentionSurface::Conversation(id(2)),
            focused_resource: Some(id(2)),
            visible_contact_ids: vec![id(2)],
            generation: 2,
        };
        governor.apply(PolicyEvent::Attention(newer.clone()), now);
        let stale = AttentionContext { generation: 1, ..AttentionContext::default() };
        governor.apply(PolicyEvent::Attention(stale), now);
        assert_eq!(governor.snapshot(now).attention, newer);
    }

    #[test]
    fn real_activity_makes_probe_unnecessary_until_stale() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        let scope = ResourceScope::Peer(id(3));
        governor.record_evidence(scope, EvidenceKind::Rx, now);
        assert_eq!(governor.freshness(scope, now + Duration::from_secs(10)), Freshness::Live);
        assert_eq!(governor.freshness(scope, now + Duration::from_secs(121)), Freshness::Stale);
    }

    #[test]
    fn lease_expiry_is_owned_by_the_runtime_scheduler() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        let owner = id(4);
        let scope = ResourceScope::Peer(id(5));
        governor.acquire_lease(WorkDemand {
            scope,
            class: WorkClass::PeerProbe,
            reason: DemandReason::VisibleConversation,
            owner,
            expires_at: now + Duration::from_secs(10),
        });
        assert!(governor.next_lease_expiry().is_some());
        governor.release_lease(owner);
        assert!(!governor.has_active_lease(scope, now));
    }

    #[test]
    fn persistent_lease_survives_deadline_until_explicit_release() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        let owner = id(40);
        let scope = ResourceScope::Peer(id(41));
        governor.acquire_persistent_lease(WorkDemand {
            scope,
            class: WorkClass::PeerDial,
            reason: DemandReason::InstantContact,
            owner,
            expires_at: now + Duration::from_millis(1),
        });
        assert!(governor.has_active_lease(scope, now + Duration::from_secs(60)));
        assert_eq!(governor.next_lease_expiry(), None);
        governor.release_lease(owner);
        assert!(!governor.has_active_lease(scope, now + Duration::from_secs(60)));
    }

    #[test]
    fn cosmetic_visibility_lease_does_not_keep_transport_awake() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        governor.acquire_lease(WorkDemand {
            scope: ResourceScope::Peer(id(42)),
            class: WorkClass::PeerProbe,
            reason: DemandReason::VisibleContact,
            owner: id(43),
            expires_at: now + Duration::from_secs(30),
        });
        assert!(!governor.has_durable_lease(now));
        governor.acquire_persistent_lease(WorkDemand {
            scope: ResourceScope::Radio(id(44)),
            class: WorkClass::Radio,
            reason: DemandReason::RadioSession,
            owner: id(45),
            expires_at: now,
        });
        assert!(governor.has_durable_lease(now));
    }

    #[test]
    fn active_peer_ids_excludes_non_peer_and_expired_work() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        governor.acquire_lease(WorkDemand {
            scope: ResourceScope::Relay,
            class: WorkClass::RelayProbe,
            reason: DemandReason::ActivePairing,
            owner: id(49),
            expires_at: now + Duration::from_secs(30),
        });
        governor.acquire_lease(WorkDemand {
            scope: ResourceScope::Peer(id(50)),
            class: WorkClass::PeerDial,
            reason: DemandReason::PendingMessage,
            owner: id(51),
            expires_at: now + Duration::from_secs(30),
        });
        governor.acquire_lease(WorkDemand {
            scope: ResourceScope::Radio(id(52)),
            class: WorkClass::Radio,
            reason: DemandReason::RadioSession,
            owner: id(53),
            expires_at: now - Duration::from_millis(1),
        });
        assert_eq!(governor.active_peer_ids(now), [id(50)].into_iter().collect());
    }

    #[test]
    fn focus_is_single_and_replaces_previous_contact() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        let first = governor.acquire_focus(id(10), id(11), now + Duration::from_secs(60), now);
        assert!(governor.is_focused(id(10), now));
        let second = governor.acquire_focus(id(12), id(13), now + Duration::from_secs(60), now);
        assert_ne!(first.owner, second.owner);
        assert!(!governor.is_focused(id(10), now));
        assert!(governor.is_focused(id(12), now));
        let snapshot = governor.snapshot(now);
        assert!(snapshot.focus_active);
        assert_eq!(snapshot.active_lease_reasons.get(&DemandReason::FocusedConversation), Some(&1));
    }

    #[test]
    fn expired_focus_is_removed_without_periodic_cleanup() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        governor.acquire_focus(id(20), id(21), now + Duration::from_millis(1), now);
        let later = now + Duration::from_millis(2);
        assert_eq!(governor.focus(later), None);
        assert!(!governor.snapshot(later).focus_active);
    }

    #[test]
    fn persistent_focus_requires_explicit_release_not_a_timer() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        let owner = id(81);
        governor.acquire_persistent_focus(id(80), owner, now);
        assert!(governor.is_focused(id(80), now + Duration::from_secs(60 * 60)));
        assert_eq!(governor.next_lease_expiry(), None);
        governor.release_lease(owner);
        assert!(!governor.is_focused(id(80), now + Duration::from_secs(60 * 60)));
    }

    #[test]
    fn idle_governor_has_no_scheduled_work_or_active_leases() {
        let now = Instant::now();
        let mut governor = RuntimeGovernor::new(now);
        assert_eq!(governor.snapshot(now).active_leases, 0);
    }

    #[test]
    fn thirty_minute_idle_does_not_create_background_work() {
        let start = Instant::now();
        let mut governor = RuntimeGovernor::new(start);
        for step in 0..=360 {
            let now = start + Duration::from_secs(step * 5);
            let snapshot = governor.snapshot(now);
            assert_eq!(snapshot.active_leases, 0);
            assert_eq!(snapshot.active_demands, 0);
            assert_eq!(snapshot.scheduled_deadlines, 0);
        }
    }

    #[test]
    fn event_hub_sleeps_until_publish() {
        let hub = RuntimeEventHub::default();
        assert_eq!(hub.current(), Some((0, 0)));
        hub.publish(7);
        assert_eq!(hub.wait(1, 0, 0, Duration::ZERO), Some((1, 7)));
    }

    #[test]
    fn event_hub_cancellation_does_not_look_like_a_runtime_change() {
        let hub = RuntimeEventHub::default();
        hub.cancel(9);
        assert_eq!(hub.wait(9, 0, 0, Duration::ZERO), None);
        assert_eq!(hub.current(), Some((0, 0)));
        // Cancellation is one-shot; the same waiter token can be reused.
        hub.publish(1);
        assert_eq!(hub.wait(9, 0, 0, Duration::ZERO), Some((1, 1)));
    }

    #[test]
    fn event_hub_cancellation_is_scoped_to_one_consumer() {
        let hub = RuntimeEventHub::default();
        hub.cancel(11);
        assert_eq!(hub.wait(11, 0, 0, Duration::ZERO), None);
        assert_eq!(hub.wait(12, 0, 0, Duration::ZERO), None);
        hub.publish(4);
        assert_eq!(hub.wait(12, 0, 0, Duration::ZERO), Some((1, 4)));
    }

    #[test]
    fn event_hub_indefinite_wait_wakes_on_revision() {
        let hub = std::sync::Arc::new(RuntimeEventHub::default());
        let producer = std::thread::spawn({
            let hub = std::sync::Arc::clone(&hub);
            move || {
                std::thread::sleep(Duration::from_millis(1));
                hub.publish(3);
            }
        });
        assert_eq!(hub.wait_indefinitely(4, 0, 0), Some((1, 3)));
        producer.join().expect("producer");
    }

    #[test]
    fn event_hub_stats_count_real_wait_outcomes() {
        let hub = RuntimeEventHub::default();
        assert_eq!(hub.wait(1, 0, 0, Duration::ZERO), None);
        hub.publish(1);
        assert_eq!(hub.wait(1, 0, 0, Duration::ZERO), Some((1, 1)));
        let stats = hub.stats().expect("stats");
        assert_eq!(stats.waits, 2);
        assert_eq!(stats.timeouts, 1);
        assert_eq!(stats.wakeups, 1);
    }
}
