[package]
name = "torca-peer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
torca-foundation = { path = "../../foundation/torca-foundation" }
torca-peer-protocol = { path = "../../protocol/torca-peer-protocol" }

[lints]
workspace = true
