//! Persistent, dev-only host for Torca soak bots.
//!
//! The host owns process lifetimes and durable bot roots. It deliberately uses
//! a tiny loopback HTTP/JSON protocol instead of adding a web framework to the
//! production workspace. The service is not a relay and must never be exposed
//! outside a controlled soak network.

use std::collections::HashMap;
use std::io::{BufRead, BufReader, Read, Write};
use std::net::{TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::process::{Child, ChildStdin, ChildStdout, Command, Stdio};
use std::sync::{Arc, Mutex};
use std::thread;

use clap::Parser;
use serde_json::{Value, json};

#[derive(Parser, Debug)]
#[command(name = "torca-soak-bot-host")]
struct Cli {
    /// Persistent root containing one directory per bot. Never point this at a
    /// normal Torca profile.
    #[arg(long, default_value = ".torca/soak/bots")]
    root: PathBuf,
    /// Already-built torca-lab-peer executable.
    #[arg(long)]
    peer_executable: PathBuf,
    #[arg(long, default_value_t = 5)]
    bots: usize,
    #[arg(long, default_value = "127.0.0.1:47890")]
    listen: String,
    /// Required on every request; generated by the launcher if omitted.
    #[arg(long)]
    token: Option<String>,
}

struct Bot {
    child: Child,
    input: ChildStdin,
    output: BufReader<ChildStdout>,
}

impl Bot {
    fn is_alive(&mut self) -> bool {
        self.child.try_wait().is_ok_and(|status| status.is_none())
    }

    fn request(&mut self, request: &Value) -> Result<Value, String> {
        serde_json::to_writer(&mut self.input, request).map_err(|e| e.to_string())?;
        self.input.write_all(b"\n").map_err(|e| e.to_string())?;
        self.input.flush().map_err(|e| e.to_string())?;
        let mut line = String::new();
        self.output.read_line(&mut line).map_err(|e| e.to_string())?;
        if line.trim().is_empty() {
            return Err("bot returned an empty response".into());
        }
        serde_json::from_str(&line).map_err(|e| format!("decode bot response: {e}"))
    }
}

impl Drop for Bot {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

type SharedBots = Arc<Mutex<HashMap<String, Bot>>>;

fn main() {
    if let Err(error) = run() {
        eprintln!("torca-soak-bot-host: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let cli = Cli::parse();
    if cli.bots == 0 || cli.bots > 20 {
        return Err("bots must be between 1 and 20".into());
    }
    let token =
        cli.token.or_else(|| std::env::var("TORCA_SOAK_BOT_TOKEN").ok()).unwrap_or_default();
    if token.trim().len() < 16 {
        return Err("--token must contain at least 16 characters".into());
    }
    std::fs::create_dir_all(&cli.root).map_err(|e| format!("create bot root: {e}"))?;
    let bots = Arc::new(Mutex::new(HashMap::new()));
    for index in 0..cli.bots {
        let name = format!("peer-{}", (b'a' + index as u8) as char);
        let root = cli.root.join(&name);
        std::fs::create_dir_all(&root).map_err(|e| format!("create {name} root: {e}"))?;
        let bot = spawn_bot(&cli.peer_executable, &root, &name)?;
        bots.lock().map_err(|_| "bot registry poisoned")?.insert(name, bot);
    }
    let listener =
        TcpListener::bind(&cli.listen).map_err(|e| format!("bind {}: {e}", cli.listen))?;
    eprintln!("torca-soak-bot-host: listening on {} with {} persistent bots", cli.listen, cli.bots);
    for stream in listener.incoming() {
        match stream {
            Ok(stream) => {
                let bots = Arc::clone(&bots);
                let token = token.clone();
                thread::spawn(move || {
                    if let Err(error) = handle_connection(stream, &token, &bots) {
                        eprintln!("torca-soak-bot-host: request failed: {error}");
                    }
                });
            }
            Err(error) => eprintln!("torca-soak-bot-host: accept failed: {error}"),
        }
    }
    Ok(())
}

fn spawn_bot(executable: &Path, root: &Path, name: &str) -> Result<Bot, String> {
    let mut child = Command::new(executable)
        .args(["--root", root.to_string_lossy().as_ref(), "--control-stdio"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| format!("spawn {name}: {e}"))?;
    let input = child.stdin.take().ok_or_else(|| format!("{name} stdin unavailable"))?;
    let output = child.stdout.take().ok_or_else(|| format!("{name} stdout unavailable"))?;
    Ok(Bot { child, input, output: BufReader::new(output) })
}

fn handle_connection(mut stream: TcpStream, token: &str, bots: &SharedBots) -> Result<(), String> {
    let (head, body) = read_http_request(&mut stream)?;
    let mut lines = head.lines();
    let request_line = lines.next().ok_or("missing request line")?;
    let mut parts = request_line.split_whitespace();
    let method = parts.next().unwrap_or_default();
    let path = parts.next().unwrap_or_default();
    let auth = lines
        .find_map(|line| line.strip_prefix("X-Torca-Soak-Token:").map(str::trim))
        .unwrap_or_default();
    if auth != token {
        return write_response(&mut stream, 401, json!({"status":"failed","error":"unauthorized"}));
    }
    if method == "GET" && path == "/health" {
        let mut registry = bots.lock().map_err(|_| "bot registry poisoned")?;
        let mut ready = Vec::new();
        let mut stopped = Vec::new();
        for (name, bot) in registry.iter_mut() {
            if bot.is_alive() {
                ready.push(name.clone());
            } else {
                stopped.push(name.clone());
            }
        }
        let status = if stopped.is_empty() { "succeeded" } else { "degraded" };
        return write_response(
            &mut stream,
            200,
            json!({"status":status,"ready":ready,"stopped":stopped}),
        );
    }
    if method != "POST" || !path.starts_with("/bot/") {
        return write_response(&mut stream, 404, json!({"status":"failed","error":"not_found"}));
    }
    let name = path.trim_start_matches("/bot/");
    let request: Value =
        serde_json::from_str(body.trim()).map_err(|e| format!("decode request: {e}"))?;
    let response = {
        let mut registry = bots.lock().map_err(|_| "bot registry poisoned")?;
        let bot = registry.get_mut(name).ok_or_else(|| format!("unknown bot {name}"))?;
        if !bot.is_alive() {
            return write_response(
                &mut stream,
                503,
                json!({"status":"failed","error":"bot_process_stopped","bot":name}),
            );
        }
        let mut request = request;
        if request.get("id").is_none() {
            request["id"] = json!("host-request");
        }
        bot.request(&request)?
    };
    write_response(&mut stream, 200, response)
}

fn read_http_request(stream: &mut TcpStream) -> Result<(String, String), String> {
    let mut header = Vec::new();
    let mut byte = [0_u8; 1];
    while !header.ends_with(b"\r\n\r\n") {
        stream.read_exact(&mut byte).map_err(|e| format!("read request header: {e}"))?;
        header.push(byte[0]);
        if header.len() > 32 * 1024 {
            return Err("request header is too large".into());
        }
    }
    let head =
        String::from_utf8(header).map_err(|e| format!("request header is not UTF-8: {e}"))?;
    let content_length = head
        .lines()
        .find_map(|line| {
            line.strip_prefix("Content-Length:")
                .and_then(|value| value.trim().parse::<usize>().ok())
        })
        .unwrap_or(0);
    if content_length > 8 * 1024 * 1024 {
        return Err("request body is too large".into());
    }
    let mut body = vec![0_u8; content_length];
    stream.read_exact(&mut body).map_err(|e| format!("read request body: {e}"))?;
    let head = head.trim_end_matches("\r\n\r\n").to_owned();
    let body = String::from_utf8(body).map_err(|e| format!("request body is not UTF-8: {e}"))?;
    Ok((head, body))
}

fn write_response(stream: &mut TcpStream, status: u16, value: Value) -> Result<(), String> {
    let body = value.to_string();
    let reason = if status == 200 {
        "OK"
    } else if status == 401 {
        "Unauthorized"
    } else {
        "Not Found"
    };
    write!(stream, "HTTP/1.1 {status} {reason}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}", body.len())
        .map_err(|e| format!("write response: {e}"))
}

#[cfg(test)]
mod tests {
    #[test]
    fn bot_names_are_stable() {
        assert_eq!(format!("peer-{}", (b'a' + 4) as char), "peer-e");
    }
}
