[package]
name = "torca-transport-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
torca-transport-api = { path = "../../application/torca-transport-api" }

[lints]
workspace = true
