FROM rust:1.94-bookworm AS builder
WORKDIR /src
COPY infra/docker/Cargo.server.toml ./Cargo.toml
COPY Cargo.lock ./
COPY common ./common
COPY server ./server
COPY infra/db ./infra/db
RUN cargo build --release -p torchat-server

FROM debian:bookworm-slim
RUN useradd --system --uid 10001 --create-home torchat
COPY --from=builder /src/target/release/torchat-server /usr/local/bin/torchat-server
USER torchat
ENV TORCHAT_BIND=0.0.0.0:8080
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/torchat-server"]
