use core::fmt::Write as _;
use torca_bridge::{BridgeResult, BridgeSnapshot, CONTRACT_VERSION};

pub(crate) fn success_result(kind:&str)->String{bridge_result_json(&BridgeResult{ok:true,kind:kind.to_owned(),error:None})}
pub(crate) fn error_result(error:&str)->String{bridge_result_json(&BridgeResult{ok:false,kind:"error".into(),error:Some(error.to_owned())})}
pub(crate) fn bridge_result_json(result:&BridgeResult)->String{let mut o=String::from("{\"ok\":");o.push_str(if result.ok{"true"}else{"false"});o.push_str(",\"kind\":\"");push_json_string(&result.kind,&mut o);o.push_str("\",\"error\":");match &result.error{Some(e)=>{o.push('"');push_json_string(e,&mut o);o.push('"')}None=>o.push_str("null")};o.push('}');o}
pub(crate) fn empty_snapshot_json()->String{format!("{{\"contractVersion\":{CONTRACT_VERSION},\"identity\":null,\"torState\":\"stopped\",\"onionAddress\":null,\"pairings\":[],\"contacts\":[],\"conversations\":[],\"messages\":[],\"attachments\":[]}}")}
pub(crate) fn bridge_snapshot_json(s:&BridgeSnapshot)->String{
 let mut o=String::new();let _=write!(o,"{{\"contractVersion\":{}",s.contract_version);o.push_str(",\"identity\":");match &s.identity_name{Some(n)=>{o.push_str("{\"displayName\":\"");push_json_string(n,&mut o);o.push_str("\"}")}None=>o.push_str("null")};o.push_str(",\"torState\":\"");push_json_string(&s.tor_state,&mut o);o.push('"');o.push_str(",\"onionAddress\":");match &s.onion_address{Some(v)=>{o.push('"');push_json_string(v,&mut o);o.push('"')}None=>o.push_str("null")};
 o.push_str(",\"pairings\":[");for(i,p)in s.pairings.iter().enumerate(){if i!=0{o.push(',')}o.push_str("{\"id\":\"");push_json_string(&p.id,&mut o);o.push_str("\",\"code\":\"");push_json_string(&p.code,&mut o);o.push_str("\",\"role\":\"");push_json_string(&p.role,&mut o);o.push_str("\",\"state\":\"");push_json_string(&p.state,&mut o);let _=write!(o,"\",\"expiresAtMs\":{},\"localApproved\":{},\"remoteApproved\":{}}}",p.expires_at_ms,p.local_approved,p.remote_approved)}
 o.push_str("],\"contacts\":[");for(i,c)in s.contacts.iter().enumerate(){if i!=0{o.push(',')}o.push_str("{\"id\":\"");push_json_string(&c.id,&mut o);o.push_str("\",\"displayName\":\"");push_json_string(&c.display_name,&mut o);o.push_str("\",\"onionAddress\":\"");push_json_string(&c.onion_address,&mut o);o.push_str("\",\"status\":\"");push_json_string(&c.status,&mut o);o.push_str("\",\"connectionState\":\"");push_json_string(&c.connection_state,&mut o);o.push_str("\",\"safetyNumber\":\"");push_json_string(&c.safety_number,&mut o);o.push_str("\"}")}
 o.push_str("],\"conversations\":[");for(i,c)in s.conversations.iter().enumerate(){if i!=0{o.push(',')}o.push_str("{\"id\":\"");push_json_string(&c.id,&mut o);o.push_str("\",\"contactId\":\"");push_json_string(&c.contact_id,&mut o);o.push_str("\",\"status\":\"");push_json_string(&c.status,&mut o);o.push_str("\"}")}
 o.push_str("],\"messages\":[");for(i,m)in s.messages.iter().enumerate(){if i!=0{o.push(',')}o.push_str("{\"id\":\"");push_json_string(&m.id,&mut o);o.push_str("\",\"conversationId\":\"");push_json_string(&m.conversation_id,&mut o);o.push_str("\",\"body\":\"");push_json_string(&m.body,&mut o);o.push_str("\",\"direction\":\"");push_json_string(&m.direction,&mut o);o.push_str("\",\"status\":\"");push_json_string(&m.status,&mut o);o.push_str("\",\"replyToMessageId\":");match &m.reply_to_message_id{Some(v)=>{o.push('"');push_json_string(v,&mut o);o.push('"')}None=>o.push_str("null")};let _=write!(o,",\"createdAtMs\":{},\"updatedAtMs\":{},\"attemptCount\":{}}}",m.created_at_ms,m.updated_at_ms,m.attempt_count)}
 o.push_str("],\"attachments\":[");for(i,a)in s.attachments.iter().enumerate(){if i!=0{o.push(',')}o.push_str("{\"id\":\"");push_json_string(&a.id,&mut o);o.push_str("\",\"messageId\":\"");push_json_string(&a.message_id,&mut o);o.push_str("\",\"name\":\"");push_json_string(&a.name,&mut o);o.push_str("\",\"mediaType\":\"");push_json_string(&a.media_type,&mut o);let _=write!(o,"\",\"size\":{},\"status\":\"",a.size);push_json_string(&a.status,&mut o);let _=write!(o,"\",\"offset\":{}}}",a.offset)}o.push_str("]}");o}
fn push_json_string(v:&str,o:&mut String){for c in v.chars(){match c{'"'=>o.push_str("\\\""),'\\'=>o.push_str("\\\\"),'\n'=>o.push_str("\\n"),'\r'=>o.push_str("\\r"),'\t'=>o.push_str("\\t"),c if c.is_control()=>{let _=write!(o,"\\u{:04x}",c as u32);}c=>o.push(c)}}}
