[package]
name = "torca-bootstrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
torca-foundation = { path = "../../foundation/torca-foundation" }
torca-transport-api = { path = "../torca-transport-api" }

[lints]
workspace = true
