[package]
name = "torca-pairing-coordinator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
torca-foundation = { path = "../../foundation/torca-foundation" }
torca-pairing = { path = "../../domains/torca-pairing" }
torca-pairing-protocol = { path = "../../protocol/torca-pairing-protocol" }

[lints]
workspace = true
