[package]
name = "torca-rendezvous-tor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
torca-rendezvous-client = { path = "../torca-rendezvous-client" }
torca-relay-protocol = { path = "../../protocol/torca-relay-protocol" }
torca-tor = { path = "../torca-tor" }

[lints]
workspace = true
