[package]
name = "torca-projections"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
torca-contacts = { path = "../../domains/torca-contacts" }
torca-conversations = { path = "../../domains/torca-conversations" }
torca-messaging = { path = "../../domains/torca-messaging" }

[lints]
workspace = true
