[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$tempRoot = Join-Path ([IO.Path]::GetTempPath()) ("torca-evidence-test-" + [guid]::NewGuid().ToString('N'))
$evidencePath = Join-Path $tempRoot 'manual-evidence.json'
$receiptPath = Join-Path $tempRoot 'receipt.json'

try {
    New-Item -ItemType Directory -Force -Path $tempRoot | Out-Null
    & (Join-Path $repositoryRoot 'scripts/release/new-manual-evidence.ps1') `
        -RepositoryRoot $repositoryRoot `
        -OutputPath $evidencePath

    $document = Get-Content -LiteralPath $evidencePath -Raw | ConvertFrom-Json
    foreach ($test in $document.tests) {
        $test.status = 'passed'
        $test.actualRuns = [int]$test.requiredRuns
        $test.actualHours = [double]$test.requiredHours
        $test.tester = 'release-tooling-test'
        $test.startedAtUtc = [DateTimeOffset]::UtcNow.AddMinutes(-1).ToString('O')
        $test.completedAtUtc = [DateTimeOffset]::UtcNow.ToString('O')
        $test.evidence = @("test://$($test.id)")
        $test.notes = 'Generated by Test-ManualEvidence.ps1.'
    }
    $utf8 = [Text.UTF8Encoding]::new($false)
    [IO.File]::WriteAllText($evidencePath, ($document | ConvertTo-Json -Depth 10), $utf8)

    & (Join-Path $repositoryRoot 'scripts/release/check-manual-evidence.ps1') `
        -RepositoryRoot $repositoryRoot `
        -EvidencePath $evidencePath `
        -ReceiptPath $receiptPath
    if (-not (Test-Path -LiteralPath $receiptPath -PathType Leaf)) {
        throw 'Manual evidence checker did not create a receipt.'
    }

    $document.tests[0].status = 'failed'
    [IO.File]::WriteAllText($evidencePath, ($document | ConvertTo-Json -Depth 10), $utf8)
    $failedAsExpected = $false
    try {
        & (Join-Path $repositoryRoot 'scripts/release/check-manual-evidence.ps1') `
            -RepositoryRoot $repositoryRoot `
            -EvidencePath $evidencePath `
            -ReceiptPath $receiptPath
    } catch {
        $failedAsExpected = $_.Exception.Message -match 'manual evidence failed'
    }
    if (-not $failedAsExpected) {
        throw 'Manual evidence checker accepted a failed required scenario.'
    }
    Write-Output 'Torca manual evidence positive and negative tests passed.'
} finally {
    Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
}
