[package]
name = "torca-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
chacha20poly1305 = "0.10.1"
ed25519-dalek = "2.1.1"
hkdf = "0.12.4"
rand_core = { version = "0.6.4", features = ["getrandom"] }
sha2 = "0.10.9"
torca-foundation = { path = "../../foundation/torca-foundation" }
torca-identity = { path = "../../domains/torca-identity" }
torca-pairing-coordinator = { path = "../../application/torca-pairing-coordinator" }
torca-peer-protocol = { path = "../../protocol/torca-peer-protocol" }
x25519-dalek = { version = "2.0.1", features = ["reusable_secrets"] }

[lints]
workspace = true
