use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
};

use serde_json::Value;

const GENERATED_HEADER: &str = "// Generated by tools/torchat-contract-gen. Do not edit.\n";

fn main() -> Result<(), String> {
    let repo_root = find_repo_root(std::env::current_dir().map_err(|error| error.to_string())?)?;
    let manifest_path = repo_root.join("common").join("client-engine-contract.json");
    let manifest: Value = serde_json::from_str(
        &fs::read_to_string(&manifest_path).map_err(|error| error.to_string())?,
    )
    .map_err(|error| error.to_string())?;

    let methods = manifest
        .get("methods")
        .and_then(Value::as_object)
        .ok_or_else(|| "client-engine-contract.json is missing methods".to_owned())?;

    let method_names = string_list(methods.get("public"))?;

    let event_names = string_list(manifest.get("events"))?;
    let message_transport = string_list(manifest.get("messageTransportOutcomes"))?;
    let pairing_peer = string_list(manifest.get("pairingPeerOutcomes"))?;

    let android_output = repo_root
        .join("mobile")
        .join("android")
        .join("app")
        .join("src")
        .join("main")
        .join("kotlin")
        .join("org")
        .join("torchat")
        .join("generated")
        .join("EngineContract.kt");
    let dart_contract_output = repo_root
        .join("mobile")
        .join("lib")
        .join("core")
        .join("runtime")
        .join("generated")
        .join("runtime_contract.g.dart");
    let dart_models_output = repo_root
        .join("mobile")
        .join("lib")
        .join("core")
        .join("models")
        .join("generated")
        .join("runtime_models.g.dart");

    write_file(&android_output, &render_kotlin_contract(&method_names, &event_names, &message_transport, &pairing_peer))?;
    write_file(&dart_contract_output, &render_dart_contract(&method_names, &event_names))?;
    write_file(&dart_models_output, &render_dart_models(&message_transport, &pairing_peer))?;
    Ok(())
}

fn find_repo_root(mut path: PathBuf) -> Result<PathBuf, String> {
    loop {
        if path.join("REFACTOR2.MD").is_file() && path.join("Cargo.toml").is_file() {
            return Ok(path);
        }
        if !path.pop() {
            return Err("could not locate repository root".to_owned());
        }
    }
}

fn string_list(value: Option<&Value>) -> Result<Vec<String>, String> {
    let array = value
        .and_then(Value::as_array)
        .ok_or_else(|| "contract entry must be an array".to_owned())?;
    array
        .iter()
        .map(|item| {
            item.as_str()
                .map(str::to_owned)
                .ok_or_else(|| "contract array item must be a string".to_owned())
        })
        .collect()
}

fn write_file(path: &Path, contents: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| error.to_string())?;
    }
    fs::write(path, contents).map_err(|error| error.to_string())
}

fn render_kotlin_contract(
    methods: &[String],
    events: &[String],
    message_transport: &[String],
    pairing_peer: &[String],
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("package org.torchat.generated\n\n");
    out.push_str("object EngineContract {\n");
    out.push_str("    const val TYPE = \"type\"\n\n");
    for name in unique_strings(methods) {
        out.push_str(&format!(
            "    const val {} = \"{}\"\n",
            screaming_snake(name),
            name
        ));
    }
    out.push('\n');
    for name in unique_strings(events) {
        out.push_str(&format!(
            "    const val {} = \"{}\"\n",
            screaming_snake(name),
            name
        ));
    }
    out.push('\n');
    for name in unique_strings(message_transport) {
        out.push_str(&format!(
            "    const val OUTCOME_{} = \"{}\"\n",
            name,
            name
        ));
    }
    out.push('\n');
    for name in unique_strings(pairing_peer) {
        out.push_str(&format!(
            "    const val PAIRING_OUTCOME_{} = \"{}\"\n",
            name,
            name
        ));
    }
    out.push_str("}\n");
    out
}

fn render_dart_contract(methods: &[String], events: &[String]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("abstract final class RuntimeContract {\n");
    out.push_str("  static const type = 'type';\n\n");
    for name in unique_strings(methods) {
        out.push_str(&format!(
            "  static const {} = '{}';\n",
            lower_camel_identifier(name),
            name
        ));
    }
    out.push('\n');
    for name in unique_strings(events) {
        out.push_str(&format!(
            "  static const {} = '{}';\n",
            lower_camel_identifier(name),
            name
        ));
    }
    out.push_str("}\n");
    out
}

fn render_dart_models(message_transport: &[String], pairing_peer: &[String]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("class GeneratedRuntimePayload {\n");
    out.push_str("  GeneratedRuntimePayload(this._value);\n\n");
    out.push_str("  final Map<String, dynamic> _value;\n\n");
    out.push_str("  factory GeneratedRuntimePayload.fromMap(Map<String, dynamic> value) =>\n");
    out.push_str("      GeneratedRuntimePayload(Map<String, dynamic>.from(value));\n\n");
    out.push_str("  factory GeneratedRuntimePayload.fromDynamic(Object? value) =>\n");
    out.push_str("      GeneratedRuntimePayload.fromMap(Map<String, dynamic>.from(value as Map));\n\n");
    out.push_str("  static GeneratedRuntimePayload? fromDynamicOrNull(Object? value) {\n");
    out.push_str("    if (value == null) return null;\n");
    out.push_str("    return GeneratedRuntimePayload.fromDynamic(value);\n");
    out.push_str("  }\n\n");
    out.push_str("  static List<GeneratedRuntimePayload> listFromDynamicOrNull(Object? value) {\n");
    out.push_str("    if (value is! List) return const [];\n");
    out.push_str("    return value\n");
    out.push_str("        .whereType<Map>()\n");
    out.push_str("        .map((item) => GeneratedRuntimePayload.fromMap(Map<String, dynamic>.from(item)))\n");
    out.push_str("        .toList();\n");
    out.push_str("  }\n\n");
    out.push_str("  static List<GeneratedRuntimePayload> itemsFromDynamicOrNull(Object? value) {\n");
    out.push_str("    if (value is Map && value['items'] is List) {\n");
    out.push_str("      return listFromDynamicOrNull(value['items']);\n");
    out.push_str("    }\n");
    out.push_str("    return listFromDynamicOrNull(value);\n");
    out.push_str("  }\n\n");
    out.push_str("  String? string(String key) => _value[key]?.toString();\n\n");
    out.push_str("  num? number(String key) => _value[key] as num?;\n\n");
    out.push_str("  int? intValue(String key) => number(key)?.toInt();\n\n");
    out.push_str("  Object? operator [](String key) => _value[key];\n\n");
    out.push_str("  Map<String, dynamic> toMap() => Map<String, dynamic>.from(_value);\n");
    out.push_str("}\n\n");
    out.push_str("class GeneratedRuntimeResponse {\n");
    out.push_str("  const GeneratedRuntimeResponse({\n");
    out.push_str("    required this.id,\n");
    out.push_str("    required this.ok,\n");
    out.push_str("    required this.payload,\n");
    out.push_str("    required this.result,\n");
    out.push_str("    this.error,\n");
    out.push_str("    this.eventType,\n");
    out.push_str("  });\n\n");
    out.push_str("  final String? id;\n");
    out.push_str("  final bool ok;\n");
    out.push_str("  final GeneratedRuntimePayload payload;\n");
    out.push_str("  final Object? result;\n");
    out.push_str("  final String? error;\n");
    out.push_str("  final String? eventType;\n\n");
    out.push_str("  factory GeneratedRuntimeResponse.fromDynamic(Object? value) {\n");
    out.push_str("    final payload = GeneratedRuntimePayload.fromDynamic(value);\n");
    out.push_str("    return GeneratedRuntimeResponse(\n");
    out.push_str("      id: payload.string('id'),\n");
    out.push_str("      ok: payload['ok'] == true,\n");
    out.push_str("      payload: payload,\n");
    out.push_str("      result: payload['result'],\n");
    out.push_str("      error: payload.string('error'),\n");
    out.push_str("      eventType: payload.string('type'),\n");
    out.push_str("    );\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");
    out.push_str("const generatedMessageTransportOutcomes = <String>[\n");
    for value in unique_strings(message_transport) {
        out.push_str(&format!("  '{}',\n", value));
    }
    out.push_str("];\n\n");
    out.push_str("const generatedPairingPeerOutcomes = <String>[\n");
    for value in unique_strings(pairing_peer) {
        out.push_str(&format!("  '{}',\n", value));
    }
    out.push_str("];\n");
    out
}

fn unique_strings(values: &[String]) -> Vec<&str> {
    let mut seen = BTreeSet::new();
    let mut result = Vec::new();
    for value in values {
        if seen.insert(value.as_str()) {
            result.push(value.as_str());
        }
    }
    result
}

fn screaming_snake(value: &str) -> String {
    let mut out = String::new();
    let mut last_was_separator = true;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && !last_was_separator && !out.ends_with('_') {
                out.push('_');
            }
            out.push(ch.to_ascii_uppercase());
            last_was_separator = false;
        } else {
            if !out.ends_with('_') {
                out.push('_');
            }
            last_was_separator = true;
        }
    }
    out.trim_matches('_').to_owned()
}

fn lower_camel_identifier(value: &str) -> String {
    let mut out = String::new();
    let mut uppercase_next = false;
    for (index, ch) in value.chars().enumerate() {
        if ch == '_' || ch == '-' {
            uppercase_next = true;
            continue;
        }
        if index == 0 {
            out.push(ch.to_ascii_lowercase());
            continue;
        }
        if uppercase_next {
            out.push(ch.to_ascii_uppercase());
            uppercase_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}
