use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
};

use serde_json::Value;

const GENERATED_HEADER: &str = "// Generated by tools/torchat-contract-gen. Do not edit.\n";

const KOTLIN_RESPONSE_MODEL: &str = r#"data class GeneratedEngineResponse(
    val requestId: String,
    val ok: Boolean,
    val value: Any?,
    val errorCode: String? = null,
    val errorMessage: String? = null,
) {
    companion object {
        fun fromJson(envelope: JSONObject): GeneratedEngineResponse {
            require(envelope.optString(EngineContract.TYPE) == EngineContract.EVENT_RESPONSE) {
                "Expected engine response event"
            }
            val requestId = envelope.optString(EngineContract.REQUEST_ID)
            require(requestId.isNotBlank()) { "Engine response is missing requestId" }
            val result = envelope.optJSONObject(EngineContract.RESULT)
                ?: error("Engine response is missing result envelope")
            return when (val status = result.optString(EngineContract.STATUS)) {
                EngineContract.RESPONSE_STATUS_OK -> GeneratedEngineResponse(
                    requestId = requestId,
                    ok = true,
                    value = decodeGeneratedPayload(
                        result.optJSONObject(EngineContract.PAYLOAD)
                            ?: error("Engine response is missing payload envelope"),
                    ),
                )
                EngineContract.RESPONSE_STATUS_ERROR -> GeneratedEngineResponse(
                    requestId = requestId,
                    ok = false,
                    value = null,
                    errorCode = result.optString(EngineContract.CODE).takeIf { it.isNotBlank() },
                    errorMessage = result.optString(EngineContract.MESSAGE).takeIf { it.isNotBlank() },
                )
                else -> error("Unknown engine response status: $status")
            }
        }
    }
}

private fun decodeGeneratedPayload(payload: JSONObject): Any? = when (val type = payload.optString(EngineContract.TYPE)) {
        EngineContract.RESPONSE_PAYLOAD_EMPTY -> null
        EngineContract.RESPONSE_PAYLOAD_JSON -> normalizeGeneratedJson(
            payload.opt(EngineContract.VALUE),
        )
        else -> error("Unknown engine response payload type: $type")
    }

private fun normalizeGeneratedJson(value: Any?): Any? = when (value) {
    null, JSONObject.NULL -> null
    is JSONObject -> value.keys().asSequence().associateWith { key ->
        normalizeGeneratedJson(value.opt(key))
    }
    is JSONArray -> List(value.length()) { index ->
        normalizeGeneratedJson(value.opt(index))
    }
    else -> value
}
"#;

fn main() -> Result<(), String> {
    let repo_root = find_repo_root(std::env::current_dir().map_err(|error| error.to_string())?)?;
    let manifest_path = repo_root.join("common").join("client-engine-contract.json");
    let manifest: Value = serde_json::from_str(
        &fs::read_to_string(&manifest_path).map_err(|error| error.to_string())?,
    )
    .map_err(|error| error.to_string())?;

    let methods = manifest
        .get("methods")
        .and_then(Value::as_object)
        .ok_or_else(|| "client-engine-contract.json is missing methods".to_owned())?;
    let method_names = string_list(methods.get("public"))?;
    let command_types = string_list(manifest.get("commandTypes"))?;
    let engine_event_types = string_list(manifest.get("engineEventTypes"))?;
    let response_statuses = string_list(manifest.get("responseStatuses"))?;
    let response_payload_types = string_list(manifest.get("responsePayloadTypes"))?;
    let platform_fact_types = string_list(manifest.get("platformFactTypes"))?;
    let tor_phases = string_list(manifest.get("torPhases"))?;
    let runtime_event_names = string_list(manifest.get("events"))?;
    let connection_states = string_list(manifest.get("connectionStates"))?;
    let transport_phases = string_list(manifest.get("transportPhases"))?;
    let message_states = string_list(manifest.get("messageStates"))?;
    let conversation_states = string_list(manifest.get("conversationStates"))?;
    let invite_states = string_list(manifest.get("inviteStates"))?;
    let pairing_actions = string_list(manifest.get("pairingAvailableActions"))?;
    let message_transport = string_list(manifest.get("messageTransportOutcomes"))?;
    let contact_transport_policies = string_list(manifest.get("contactTransportPolicies"))?;
    let pairing_peer = string_list(manifest.get("pairingPeerOutcomes"))?;
    let peer_endpoint_statuses = string_list(manifest.get("peerEndpointStatuses"))?;
    let peer_connection_statuses = string_list(manifest.get("peerConnectionStatuses"))?;
    let platform_action_types = string_list(manifest.get("platformActionTypes"))?;

    let android_output = repo_root
        .join("apps/mobile/flutter/android/app/src/main/kotlin/org/torchat/generated/EngineContract.kt");
    let dart_contract_output =
        repo_root.join("apps/mobile/flutter/lib/core/runtime/generated/runtime_contract.g.dart");
    let dart_models_output =
        repo_root.join("apps/mobile/flutter/lib/core/models/generated/runtime_models.g.dart");

    write_file(
        &android_output,
        &render_kotlin_contract(
            &method_names,
            &command_types,
            &engine_event_types,
            &response_statuses,
            &response_payload_types,
            &platform_fact_types,
            &tor_phases,
            &runtime_event_names,
            &connection_states,
            &transport_phases,
            &message_states,
            &conversation_states,
            &invite_states,
            &pairing_actions,
            &message_transport,
            &contact_transport_policies,
            &pairing_peer,
            &peer_endpoint_statuses,
            &peer_connection_statuses,
            &platform_action_types,
        ),
    )?;
    write_file(
        &dart_contract_output,
        &render_dart_contract(
            &method_names,
            &command_types,
            &engine_event_types,
            &response_statuses,
            &response_payload_types,
            &platform_fact_types,
            &tor_phases,
            &runtime_event_names,
            &connection_states,
            &transport_phases,
            &message_states,
            &conversation_states,
            &invite_states,
            &pairing_actions,
            &message_transport,
            &contact_transport_policies,
            &pairing_peer,
            &peer_endpoint_statuses,
            &peer_connection_statuses,
            &platform_action_types,
        ),
    )?;
    write_file(
        &dart_models_output,
        &render_dart_models(
            &engine_event_types,
            &tor_phases,
            &connection_states,
            &transport_phases,
            &message_states,
            &conversation_states,
            &invite_states,
            &pairing_actions,
            &message_transport,
            &pairing_peer,
            &peer_endpoint_statuses,
            &peer_connection_statuses,
        ),
    )?;
    Ok(())
}

fn find_repo_root(mut path: PathBuf) -> Result<PathBuf, String> {
    loop {
        if path.join("Cargo.toml").is_file()
            && path
                .join("common")
                .join("client-engine-contract.json")
                .is_file()
        {
            return Ok(path);
        }
        if !path.pop() {
            return Err("could not locate repository root".to_owned());
        }
    }
}

fn string_list(value: Option<&Value>) -> Result<Vec<String>, String> {
    let array = value
        .and_then(Value::as_array)
        .ok_or_else(|| "contract entry must be an array".to_owned())?;
    array
        .iter()
        .map(|item| {
            item.as_str()
                .map(str::to_owned)
                .ok_or_else(|| "contract array item must be a string".to_owned())
        })
        .collect()
}

fn write_file(path: &Path, contents: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| error.to_string())?;
    }
    fs::write(path, contents).map_err(|error| error.to_string())
}

#[allow(clippy::too_many_arguments)]
fn render_kotlin_contract(
    methods: &[String],
    command_types: &[String],
    engine_event_types: &[String],
    response_statuses: &[String],
    response_payload_types: &[String],
    platform_fact_types: &[String],
    tor_phases: &[String],
    runtime_events: &[String],
    connection_states: &[String],
    transport_phases: &[String],
    message_states: &[String],
    conversation_states: &[String],
    invite_states: &[String],
    pairing_actions: &[String],
    message_transport: &[String],
    contact_transport_policies: &[String],
    pairing_peer: &[String],
    peer_endpoint_statuses: &[String],
    peer_connection_statuses: &[String],
    platform_action_types: &[String],
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("package org.torchat.generated\n\n");
    out.push_str("import org.json.JSONArray\n");
    out.push_str("import org.json.JSONObject\n\n");
    out.push_str("object EngineContract {\n");
    for (name, value) in wire_keys() {
        out.push_str(&format!("    const val {name} = \"{value}\"\n"));
    }
    out.push('\n');
    render_kotlin_values(&mut out, "", methods);
    out.push('\n');
    render_kotlin_values(&mut out, "COMMAND_", command_types);
    out.push('\n');
    render_kotlin_values(&mut out, "EVENT_", engine_event_types);
    out.push('\n');
    render_kotlin_values(&mut out, "RESPONSE_STATUS_", response_statuses);
    out.push('\n');
    render_kotlin_values(&mut out, "RESPONSE_PAYLOAD_", response_payload_types);
    out.push('\n');
    render_kotlin_values(&mut out, "FACT_", platform_fact_types);
    out.push('\n');
    render_kotlin_values(&mut out, "TOR_PHASE_", tor_phases);
    out.push('\n');
    render_kotlin_values(&mut out, "", runtime_events);
    out.push('\n');
    render_kotlin_values(&mut out, "CONNECTION_STATE_", connection_states);
    out.push('\n');
    render_kotlin_values(&mut out, "TRANSPORT_PHASE_", transport_phases);
    out.push('\n');
    render_kotlin_values(&mut out, "MESSAGE_STATE_", message_states);
    out.push('\n');
    render_kotlin_values(&mut out, "CONVERSATION_STATE_", conversation_states);
    out.push('\n');
    render_kotlin_values(&mut out, "INVITE_STATE_", invite_states);
    out.push('\n');
    render_kotlin_values(&mut out, "PAIRING_ACTION_", pairing_actions);
    out.push('\n');
    render_kotlin_values(&mut out, "OUTCOME_", message_transport);
    out.push('\n');
    render_kotlin_values(
        &mut out,
        "CONTACT_TRANSPORT_POLICY_",
        contact_transport_policies,
    );
    out.push('\n');
    render_kotlin_values(&mut out, "PAIRING_OUTCOME_", pairing_peer);
    out.push('\n');
    render_kotlin_values(&mut out, "PEER_ENDPOINT_STATUS_", peer_endpoint_statuses);
    out.push('\n');
    render_kotlin_values(
        &mut out,
        "PEER_CONNECTION_STATUS_",
        peer_connection_statuses,
    );
    out.push('\n');
    render_kotlin_values(&mut out, "PLATFORM_ACTION_", platform_action_types);
    out.push_str("}\n\n");
    out.push_str(KOTLIN_RESPONSE_MODEL);
    render_kotlin_event_model(&mut out, engine_event_types);
    out
}

fn render_kotlin_event_model(out: &mut String, engine_event_types: &[String]) {
    out.push_str("\n\ndata class GeneratedEngineEvent(\n");
    out.push_str("    val type: String,\n");
    out.push_str("    val envelope: JSONObject,\n");
    out.push_str(") {\n");
    out.push_str("    fun objectValue(key: String): JSONObject =\n");
    out.push_str(
        "        envelope.optJSONObject(key) ?: error(\"Engine event is missing $key object\")\n\n",
    );
    out.push_str("    companion object {\n");
    out.push_str("        private val supportedTypes = setOf(\n");
    for event_type in unique_strings(engine_event_types) {
        out.push_str(&format!(
            "            EngineContract.EVENT_{},\n",
            screaming_snake(event_type),
        ));
    }
    out.push_str("        )\n\n");
    out.push_str("        fun fromJson(envelope: JSONObject): GeneratedEngineEvent {\n");
    out.push_str("            val type = envelope.optString(EngineContract.TYPE)\n");
    out.push_str(
        "            require(type in supportedTypes) { \"Unknown engine event type: $type\" }\n",
    );
    out.push_str("            when (type) {\n");
    out.push_str("                EngineContract.EVENT_RESPONSE -> GeneratedEngineResponse.fromJson(envelope)\n");
    out.push_str("                EngineContract.EVENT_RUNTIME -> requireObject(envelope, EngineContract.EVENT)\n");
    out.push_str("                EngineContract.EVENT_CONNECTION -> requireObject(envelope, EngineContract.SNAPSHOT)\n");
    out.push_str("                EngineContract.EVENT_PLATFORM_ACTION -> requireObject(envelope, EngineContract.ACTION)\n");
    out.push_str("                EngineContract.EVENT_NOTIFICATION_REQUESTED -> requireObject(envelope, EngineContract.NOTIFICATION)\n");
    out.push_str(
        "                EngineContract.EVENT_LOG -> requireObject(envelope, EngineContract.LOG)\n",
    );
    out.push_str("                EngineContract.EVENT_FATAL -> requireObject(envelope, EngineContract.ERROR)\n");
    out.push_str("            }\n");
    out.push_str("            return GeneratedEngineEvent(type, envelope)\n");
    out.push_str("        }\n\n");
    out.push_str("        private fun requireObject(envelope: JSONObject, key: String) {\n");
    out.push_str("            require(envelope.optJSONObject(key) != null) { \"Engine event is missing $key object\" }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");
}

fn render_kotlin_values(out: &mut String, prefix: &str, values: &[String]) {
    for name in unique_strings(values) {
        out.push_str(&format!(
            "    const val {prefix}{} = \"{}\"\n",
            screaming_snake(name),
            name,
        ));
    }
}

#[allow(clippy::too_many_arguments)]
fn render_dart_contract(
    methods: &[String],
    command_types: &[String],
    engine_event_types: &[String],
    response_statuses: &[String],
    response_payload_types: &[String],
    platform_fact_types: &[String],
    tor_phases: &[String],
    runtime_events: &[String],
    connection_states: &[String],
    transport_phases: &[String],
    message_states: &[String],
    conversation_states: &[String],
    invite_states: &[String],
    pairing_actions: &[String],
    message_transport: &[String],
    contact_transport_policies: &[String],
    pairing_peer: &[String],
    peer_endpoint_statuses: &[String],
    peer_connection_statuses: &[String],
    platform_action_types: &[String],
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("abstract final class EngineContract {\n");
    for (name, value) in wire_keys() {
        let identifier = lower_camel_identifier(name);
        out.push_str(&format!("  static const {identifier} = '{value}';\n",));
    }
    out.push('\n');
    render_dart_values(&mut out, "", methods);
    out.push('\n');
    render_dart_values(&mut out, "command_", command_types);
    out.push('\n');
    render_dart_values(&mut out, "event_", engine_event_types);
    out.push('\n');
    render_dart_values(&mut out, "response_status_", response_statuses);
    out.push('\n');
    render_dart_values(&mut out, "response_payload_", response_payload_types);
    out.push('\n');
    render_dart_values(&mut out, "fact_", platform_fact_types);
    out.push('\n');
    render_dart_values(&mut out, "tor_phase_", tor_phases);
    out.push('\n');
    render_dart_values(&mut out, "", runtime_events);
    out.push('\n');
    render_dart_values(&mut out, "connection_state_", connection_states);
    out.push('\n');
    render_dart_values(&mut out, "transport_phase_", transport_phases);
    out.push('\n');
    render_dart_values(&mut out, "message_state_", message_states);
    out.push('\n');
    render_dart_values(&mut out, "conversation_state_", conversation_states);
    out.push('\n');
    render_dart_values(&mut out, "invite_state_", invite_states);
    out.push('\n');
    render_dart_values(&mut out, "pairing_action_", pairing_actions);
    out.push('\n');
    render_dart_values(&mut out, "outcome_", message_transport);
    out.push('\n');
    render_dart_values(
        &mut out,
        "contact_transport_policy_",
        contact_transport_policies,
    );
    out.push('\n');
    render_dart_values(&mut out, "pairing_outcome_", pairing_peer);
    out.push('\n');
    render_dart_values(&mut out, "peer_endpoint_status_", peer_endpoint_statuses);
    out.push('\n');
    render_dart_values(
        &mut out,
        "peer_connection_status_",
        peer_connection_statuses,
    );
    out.push('\n');
    render_dart_values(&mut out, "platform_action_", platform_action_types);
    out.push_str("  static const transportComponent = 'component';\n");
    out.push_str("  static const transportState = 'state';\n");
    out.push_str("  static const endpoint = 'endpoint';\n");
    out.push_str("  static const updatedAt = 'updatedAt';\n");
    out.push_str("}\n");
    out
}

fn render_dart_values(out: &mut String, prefix: &str, values: &[String]) {
    for name in unique_strings(values) {
        let identifier = lower_camel_identifier(&format!("{prefix}{name}"));
        out.push_str(&format!("  static const {identifier} = '{name}';\n"));
    }
}

#[allow(clippy::too_many_arguments)]
fn render_dart_models(
    engine_event_types: &[String],
    tor_phases: &[String],
    connection_states: &[String],
    transport_phases: &[String],
    message_states: &[String],
    conversation_states: &[String],
    invite_states: &[String],
    pairing_actions: &[String],
    message_transport: &[String],
    pairing_peer: &[String],
    peer_endpoint_statuses: &[String],
    peer_connection_statuses: &[String],
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("import '../../runtime/generated/runtime_contract.g.dart';\n\n");
    out.push_str("class GeneratedRuntimePayload {\n");
    out.push_str("  GeneratedRuntimePayload(this._value);\n\n");
    out.push_str("  final Map<String, dynamic> _value;\n\n");
    out.push_str("  factory GeneratedRuntimePayload.fromMap(Map<String, dynamic> value) =>\n");
    out.push_str("      GeneratedRuntimePayload(Map<String, dynamic>.from(value));\n\n");
    out.push_str("  factory GeneratedRuntimePayload.fromDynamic(Object? value) {\n");
    out.push_str("    if (value is! Map) {\n");
    out.push_str("      throw FormatException('expected JSON object payload');\n");
    out.push_str("    }\n");
    out.push_str("    return GeneratedRuntimePayload.fromMap(Map<String, dynamic>.from(value));\n");
    out.push_str("  }\n\n");
    out.push_str("  static GeneratedRuntimePayload? fromDynamicOrNull(Object? value) {\n");
    out.push_str("    if (value == null) return null;\n");
    out.push_str("    return GeneratedRuntimePayload.fromDynamic(value);\n");
    out.push_str("  }\n\n");
    out.push_str("  static List<GeneratedRuntimePayload> listFromDynamicOrNull(Object? value) {\n");
    out.push_str("    if (value is! List) return const [];\n");
    out.push_str("    return value\n");
    out.push_str("        .whereType<Map>()\n");
    out.push_str("        .map((item) => GeneratedRuntimePayload.fromMap(Map<String, dynamic>.from(item)))\n");
    out.push_str("        .toList();\n");
    out.push_str("  }\n\n");
    out.push_str(
        "  static List<GeneratedRuntimePayload> itemsFromDynamicOrNull(Object? value) {\n",
    );
    out.push_str("    if (value is Map && value[EngineContract.items] is List) {\n");
    out.push_str("      return listFromDynamicOrNull(value[EngineContract.items]);\n");
    out.push_str("    }\n");
    out.push_str("    return listFromDynamicOrNull(value);\n");
    out.push_str("  }\n\n");
    out.push_str("  String? string(String key) => _value[key]?.toString();\n\n");
    out.push_str("  num? number(String key) => _value[key] as num?;\n\n");
    out.push_str("  int? intValue(String key) => number(key)?.toInt();\n\n");
    out.push_str("  Object? operator [](String key) => _value[key];\n\n");
    out.push_str("  Map<String, dynamic> toMap() => Map<String, dynamic>.from(_value);\n");
    out.push_str("}\n\n");
    out.push_str("class GeneratedEngineEvent {\n");
    out.push_str("  const GeneratedEngineEvent({required this.type, required this.envelope});\n\n");
    out.push_str("  final String type;\n");
    out.push_str("  final Map<String, dynamic> envelope;\n\n");
    out.push_str("  factory GeneratedEngineEvent.fromDynamic(Object? value) {\n");
    out.push_str("    final payload = GeneratedRuntimePayload.fromDynamic(value);\n");
    out.push_str("    final type = payload.string(EngineContract.type);\n");
    out.push_str("    const supportedTypes = <String>{\n");
    for event_type in unique_strings(engine_event_types) {
        out.push_str(&format!(
            "      EngineContract.event{},\n",
            upper_camel_identifier(event_type),
        ));
    }
    out.push_str("    };\n");
    out.push_str("    if (type == null || !supportedTypes.contains(type)) {\n");
    out.push_str("      throw FormatException('unknown engine event type: $type');\n");
    out.push_str("    }\n");
    out.push_str("    final envelope = payload.toMap();\n");
    out.push_str("    switch (type) {\n");
    out.push_str("      case EngineContract.eventResponse:\n");
    out.push_str("        GeneratedEngineResponse.fromDynamic(envelope);\n");
    out.push_str("        break;\n");
    out.push_str("      case EngineContract.eventRuntime:\n");
    out.push_str("        _requireGeneratedEventObject(envelope, EngineContract.event);\n");
    out.push_str("        break;\n");
    out.push_str("      case EngineContract.eventConnection:\n");
    out.push_str("        _requireGeneratedEventObject(envelope, EngineContract.snapshot);\n");
    out.push_str("        break;\n");
    out.push_str("      case EngineContract.eventPlatformAction:\n");
    out.push_str("        _requireGeneratedEventObject(envelope, EngineContract.action);\n");
    out.push_str("        break;\n");
    out.push_str("      case EngineContract.eventNotificationRequested:\n");
    out.push_str("        _requireGeneratedEventObject(envelope, EngineContract.notification);\n");
    out.push_str("        break;\n");
    out.push_str("      case EngineContract.eventLog:\n");
    out.push_str("        _requireGeneratedEventObject(envelope, EngineContract.log);\n");
    out.push_str("        break;\n");
    out.push_str("      case EngineContract.eventFatal:\n");
    out.push_str("        _requireGeneratedEventObject(envelope, EngineContract.error);\n");
    out.push_str("        break;\n");
    out.push_str("    }\n");
    out.push_str("    return GeneratedEngineEvent(type: type, envelope: envelope);\n");
    out.push_str("  }\n\n");
    out.push_str("  Map<String, dynamic> objectValue(String key) =>\n");
    out.push_str("      _requireGeneratedEventObject(envelope, key);\n");
    out.push_str("}\n\n");
    out.push_str("Map<String, dynamic> _requireGeneratedEventObject(\n");
    out.push_str("  Map<String, dynamic> envelope,\n");
    out.push_str("  String key,\n");
    out.push_str(") {\n");
    out.push_str("  final value = envelope[key];\n");
    out.push_str("  if (value is! Map) {\n");
    out.push_str("    throw FormatException('engine event is missing $key object');\n");
    out.push_str("  }\n");
    out.push_str("  return Map<String, dynamic>.from(value);\n");
    out.push_str("}\n\n");
    out.push_str("class GeneratedEngineResponse {\n");
    out.push_str("  const GeneratedEngineResponse({\n");
    out.push_str("    required this.requestId,\n");
    out.push_str("    required this.ok,\n");
    out.push_str("    required this.result,\n");
    out.push_str("    this.errorCode,\n");
    out.push_str("    this.errorMessage,\n");
    out.push_str("  });\n\n");
    out.push_str("  final String requestId;\n");
    out.push_str("  final bool ok;\n");
    out.push_str("  final Object? result;\n");
    out.push_str("  final String? errorCode;\n");
    out.push_str("  final String? errorMessage;\n\n");
    out.push_str("  factory GeneratedEngineResponse.fromDynamic(Object? value) {\n");
    out.push_str("    final envelope = GeneratedRuntimePayload.fromDynamic(value);\n");
    out.push_str(
        "    if (envelope.string(EngineContract.type) != EngineContract.eventResponse) {\n",
    );
    out.push_str("      throw FormatException('expected engine response event');\n");
    out.push_str("    }\n");
    out.push_str("    final requestId = envelope.string(EngineContract.requestId);\n");
    out.push_str("    if (requestId == null || requestId.isEmpty) {\n");
    out.push_str("      throw FormatException('engine response is missing requestId');\n");
    out.push_str("    }\n");
    out.push_str("    final rawResult = envelope[EngineContract.result];\n");
    out.push_str("    if (rawResult is! Map) {\n");
    out.push_str("      throw FormatException('engine response is missing result envelope');\n");
    out.push_str("    }\n");
    out.push_str("    final resultEnvelope = GeneratedRuntimePayload.fromMap(Map<String, dynamic>.from(rawResult));\n");
    out.push_str("    final status = resultEnvelope.string(EngineContract.status);\n");
    out.push_str("    if (status == EngineContract.responseStatusOk) {\n");
    out.push_str("      final rawPayload = resultEnvelope[EngineContract.payload];\n");
    out.push_str("      if (rawPayload is! Map) {\n");
    out.push_str("        throw FormatException('engine response is missing payload envelope');\n");
    out.push_str("      }\n");
    out.push_str("      final payload = GeneratedRuntimePayload.fromMap(Map<String, dynamic>.from(rawPayload));\n");
    out.push_str("      final payloadType = payload.string(EngineContract.type);\n");
    out.push_str("      final Object? decodedResult;\n");
    out.push_str("      if (payloadType == EngineContract.responsePayloadEmpty) {\n");
    out.push_str("        decodedResult = null;\n");
    out.push_str("      } else if (payloadType == EngineContract.responsePayloadJson) {\n");
    out.push_str("        decodedResult = payload[EngineContract.value];\n");
    out.push_str("      } else {\n");
    out.push_str("        throw FormatException(\n");
    out.push_str("          'unknown engine response payload type: $payloadType',\n");
    out.push_str("        );\n");
    out.push_str("      }\n");
    out.push_str("      return GeneratedEngineResponse(\n");
    out.push_str("        requestId: requestId,\n");
    out.push_str("        ok: true,\n");
    out.push_str("        result: decodedResult,\n");
    out.push_str("      );\n");
    out.push_str("    }\n");
    out.push_str("    if (status == EngineContract.responseStatusError) {\n");
    out.push_str("      return GeneratedEngineResponse(\n");
    out.push_str("        requestId: requestId,\n");
    out.push_str("        ok: false,\n");
    out.push_str("        result: null,\n");
    out.push_str("        errorCode: resultEnvelope.string(EngineContract.code),\n");
    out.push_str("        errorMessage: resultEnvelope.string(EngineContract.message),\n");
    out.push_str("      );\n");
    out.push_str("    }\n");
    out.push_str("    throw FormatException('unknown engine response status: $status');\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");
    render_dart_string_list(&mut out, "generatedTorPhases", tor_phases);
    render_dart_string_list(&mut out, "generatedConnectionStates", connection_states);
    render_dart_string_list(&mut out, "generatedTransportPhases", transport_phases);
    render_dart_string_list(&mut out, "generatedMessageStates", message_states);
    render_dart_string_list(&mut out, "generatedConversationStates", conversation_states);
    render_dart_string_list(&mut out, "generatedInviteStates", invite_states);
    render_dart_string_list(
        &mut out,
        "generatedPairingAvailableActions",
        pairing_actions,
    );
    render_dart_string_list(
        &mut out,
        "generatedMessageTransportOutcomes",
        message_transport,
    );
    render_dart_string_list(&mut out, "generatedPairingPeerOutcomes", pairing_peer);
    render_dart_string_list(
        &mut out,
        "generatedPeerEndpointStatuses",
        peer_endpoint_statuses,
    );
    render_dart_string_list(
        &mut out,
        "generatedPeerConnectionStatuses",
        peer_connection_statuses,
    );
    out
}

fn render_dart_string_list(out: &mut String, name: &str, values: &[String]) {
    out.push_str(&format!("const {name} = <String>[\n"));
    for value in unique_strings(values) {
        out.push_str(&format!("  '{}',\n", value));
    }
    out.push_str("];\n\n");
}

fn wire_keys() -> &'static [(&'static str, &'static str)] {
    &[
        ("TYPE", "type"),
        ("REQUEST_ID", "requestId"),
        ("COMMAND_ID", "commandId"),
        ("REVISION", "revision"),
        ("COMMAND", "command"),
        ("RESULT", "result"),
        ("STATUS", "status"),
        ("PAYLOAD", "payload"),
        ("VALUE", "value"),
        ("CODE", "code"),
        ("MESSAGE", "message"),
        ("EVENT", "event"),
        ("SNAPSHOT", "snapshot"),
        ("NOTIFICATION", "notification"),
        ("LOG", "log"),
        ("ERROR", "error"),
        ("FACT", "fact"),
        ("ACTION", "action"),
        ("NICKNAME", "nickname"),
        ("COMMAND_PAIRING_ID", "pairing_id"),
        ("COMMAND_CONVERSATION_ID", "conversation_id"),
        ("COMMAND_INSTALLATION_ID", "installation_id"),
        ("COMMAND_CONTACT_ID", "contact_id"),
        ("COMMAND_REPLY_TO_MESSAGE_ID", "reply_to_message_id"),
        ("FACT_SOCKS5_URL", "socks5_url"),
        ("FACT_ONION_ADDRESS", "onion_address"),
        ("FACT_VIRTUAL_PORT", "virtual_port"),
        ("FACT_BATTERY_SAVER", "battery_saver"),
        ("FACT_DEVICE_IDLE", "device_idle"),
        ("ONION_ADDRESS", "onionAddress"),
        ("VIRTUAL_PORT", "virtualPort"),
        ("SEQUENCE", "sequence"),
        ("ISSUED_AT", "issuedAt"),
        ("CAPABILITIES", "capabilities"),
        ("LOCAL_PORT", "localPort"),
        ("GENERATION", "generation"),
        ("ONLINE", "online"),
        ("BATTERY_SAVER", "batterySaver"),
        ("DEVICE_IDLE", "deviceIdle"),
        ("RESTRICTED", "restricted"),
        ("PAIRING_ID", "pairingId"),
        ("PAIR_KEY", "pairKey"),
        ("CONVERSATION_ID", "conversationId"),
        ("INSTALLATION_ID", "installationId"),
        ("CONTACT_ID", "contactId"),
        ("SOCKS5_URL", "socks5Url"),
        ("PUBLIC_KEY", "publicKey"),
        ("FINGERPRINT", "fingerprint"),
        ("VERIFICATION", "verification"),
        ("DEV", "dev"),
        ("LOCAL_ALIAS", "localAlias"),
        ("MUTED", "muted"),
        ("BLOCKED", "blocked"),
        ("PEER_ENDPOINT_STATUS", "peerEndpointStatus"),
        ("PEER_CONNECTION_STATUS", "peerConnectionStatus"),
        ("LAST_PEER_CONNECTED_AT", "lastPeerConnectedAt"),
        ("LAST_SEEN_AT", "lastSeenAt"),
        ("TRANSPORT_POLICY", "transportPolicy"),
        ("CONTACT_INSTALLATION_ID", "contactInstallationId"),
        ("LAST_MESSAGE_PREVIEW", "lastMessagePreview"),
        ("LAST_MESSAGE_AT", "lastMessageAt"),
        ("UNREAD_COUNT", "unreadCount"),
        ("OUTGOING", "outgoing"),
        ("CREATED_AT", "createdAt"),
        ("ATTEMPT_COUNT", "attemptCount"),
        ("LAST_ATTEMPT_AT", "lastAttemptAt"),
        ("NEXT_ATTEMPT_AT", "nextAttemptAt"),
        ("ACK_DEADLINE", "ackDeadline"),
        ("LAST_TRANSPORT_ERROR", "lastTransportError"),
        ("EXPIRES_AT", "expiresAt"),
        ("AVAILABLE_ACTIONS", "availableActions"),
        ("SENDER", "sender"),
        ("CAPABILITY", "capability"),
        ("RECEIVED", "received"),
        ("OFFER_INVITE_ID", "offerInviteId"),
        ("OFFER_PAYLOAD", "offerPayload"),
        ("PROTOCOL", "protocol"),
        ("PROFILE", "profile"),
        ("KIND", "kind"),
        ("MESSAGE_ID", "messageId"),
        ("REPLY_TO", "replyTo"),
        ("TEXT", "text"),
        ("ITEMS", "items"),
        ("LEVEL", "level"),
        ("BODY", "body"),
        ("TYPING", "typing"),
        ("FOCUSED", "focused"),
        ("IDLE", "idle"),
        ("OBSERVED_AT", "observedAt"),
        ("PHASE", "phase"),
        ("PROGRESS", "progress"),
        ("DETAIL", "detail"),
        ("FOREGROUND", "foreground"),
        ("REASON", "reason"),
        ("TITLE", "title"),
        ("ID", "id"),
        ("STATE", "state"),
        ("BACKOFF", "backoff"),
        ("ATTEMPT", "attempt"),
        ("RETRY_IN_MS", "retryInMs"),
        ("LABEL", "label"),
        ("RETRY_ATTEMPT", "retryAttempt"),
        ("LATENCY_MS", "latencyMs"),
        ("DATABASE_PATH", "databasePath"),
        ("DATABASE_KEY", "databaseKey"),
        ("IDENTITY_PRIVATE_KEY", "identityPrivateKey"),
        ("RELAY_ONION_URL", "relayOnionUrl"),
        ("INITIAL_SOCKS5_URL", "initialSocks5Url"),
        ("LOG_DIRECTORY", "logDirectory"),
        ("PLATFORM", "platform"),
        ("ARG_PAIRING_ID", "pairingId"),
        ("ARG_INSTALLATION_ID", "installationId"),
        ("ARG_CONTACT_ID", "contactId"),
        ("ARG_ID", "id"),
        ("ARG_TEXT", "text"),
        ("ARG_REPLY_TO_MESSAGE_ID", "replyToMessageId"),
    ]
}

fn unique_strings(values: &[String]) -> Vec<&str> {
    let mut seen = BTreeSet::new();
    let mut result = Vec::new();
    for value in values {
        if seen.insert(value.as_str()) {
            result.push(value.as_str());
        }
    }
    result
}

fn screaming_snake(value: &str) -> String {
    if value
        .chars()
        .all(|ch| ch.is_ascii_uppercase() || ch.is_ascii_digit() || ch == '_')
    {
        return value.to_owned();
    }
    let mut out = String::new();
    let mut last_was_separator = true;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && !last_was_separator && !out.ends_with('_') {
                out.push('_');
            }
            out.push(ch.to_ascii_uppercase());
            last_was_separator = false;
        } else {
            if !out.ends_with('_') {
                out.push('_');
            }
            last_was_separator = true;
        }
    }
    out.trim_matches('_').to_owned()
}

fn upper_camel_identifier(value: &str) -> String {
    let lower = lower_camel_identifier(value);
    let mut chars = lower.chars();
    match chars.next() {
        Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

fn lower_camel_identifier(value: &str) -> String {
    if value.contains('_') || value.contains('-') {
        let mut words = value
            .split(['_', '-'])
            .filter(|word| !word.is_empty())
            .map(str::to_ascii_lowercase);
        let Some(first) = words.next() else {
            return String::new();
        };
        let mut out = first;
        for word in words {
            let mut chars = word.chars();
            if let Some(first) = chars.next() {
                out.push(first.to_ascii_uppercase());
                out.push_str(chars.as_str());
            }
        }
        return out;
    }

    if value
        .chars()
        .all(|ch| ch.is_ascii_uppercase() || ch.is_ascii_digit())
    {
        return value.to_ascii_lowercase();
    }

    let mut chars = value.chars();
    match chars.next() {
        Some(first) => first.to_ascii_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}
