use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
};

use serde::Deserialize;

const HEADER: &str = "// Generated by tools/torchat-contract-gen. Do not edit.\n\n";

#[derive(Debug, Deserialize)]
struct Manifest {
    protocol: u16,
    commands: Vec<Command>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Command {
    public_method: String,
    wire_name: String,
    category: String,
    durable: bool,
    requires_command_id: bool,
    idempotent: bool,
    handler_key: String,
}

fn main() -> Result<(), String> {
    let root = find_repo_root(std::env::current_dir().map_err(|error| error.to_string())?)?;
    let manifest_path = root.join("common/client-engine-contract.json");
    let manifest: Manifest = serde_json::from_str(
        &fs::read_to_string(&manifest_path).map_err(|error| error.to_string())?,
    )
    .map_err(|error| error.to_string())?;
    validate(&manifest)?;

    write(
        &root.join("packages/torchat-client-engine/src/generated/command_contract.rs"),
        &render_rust(&manifest),
    )?;
    write(
        &root.join("apps/mobile/flutter/lib/core/runtime/generated/command_contract.g.dart"),
        &render_dart(&manifest),
    )?;
    write(
        &root.join(
            "apps/mobile/flutter/android/app/src/main/kotlin/org/torchat/generated/GeneratedCommandContract.kt",
        ),
        &render_kotlin(&manifest),
    )?;
    Ok(())
}

fn validate(manifest: &Manifest) -> Result<(), String> {
    if manifest.protocol == 0 {
        return Err("protocol must be greater than zero".to_owned());
    }
    if manifest.commands.is_empty() {
        return Err("commands must not be empty".to_owned());
    }
    let mut public_methods = BTreeSet::new();
    let mut wire_names = BTreeSet::new();
    let mut handlers = BTreeSet::new();
    for command in &manifest.commands {
        for (label, value) in [
            ("publicMethod", command.public_method.as_str()),
            ("wireName", command.wire_name.as_str()),
            ("category", command.category.as_str()),
            ("handlerKey", command.handler_key.as_str()),
        ] {
            if value.trim().is_empty() {
                return Err(format!("{label} must not be empty"));
            }
        }
        if !public_methods.insert(command.public_method.as_str()) {
            return Err(format!("duplicate publicMethod: {}", command.public_method));
        }
        if !wire_names.insert(command.wire_name.as_str()) {
            return Err(format!("duplicate wireName: {}", command.wire_name));
        }
        if !handlers.insert(command.handler_key.as_str()) {
            return Err(format!("duplicate handlerKey: {}", command.handler_key));
        }
        if command.durable && !command.requires_command_id {
            return Err(format!(
                "durable command {} must require commandId",
                command.wire_name
            ));
        }
        if command.requires_command_id && !command.idempotent {
            return Err(format!(
                "command {} requires commandId but is not idempotent",
                command.wire_name
            ));
        }
    }
    Ok(())
}

fn render_rust(manifest: &Manifest) -> String {
    let mut output = String::from(HEADER);
    output.push_str(
        "use serde::{Deserialize, Serialize};\n\n\
         #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n\
         #[serde(rename_all = \"camelCase\")]\n\
         pub struct GeneratedCommandRequest {\n\
         \t#[serde(rename = \"type\")]\n\
         \tpub command_type: String,\n\
         \t#[serde(skip_serializing_if = \"Option::is_none\")]\n\
         \tpub command_id: Option<String>,\n\
         \t#[serde(default)]\n\
         \tpub payload: serde_json::Value,\n\
         }\n\n\
         #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]\n\
         #[serde(rename_all = \"camelCase\")]\n\
         pub struct GeneratedCommandResponse {\n\
         \tpub status: String,\n\
         \t#[serde(skip_serializing_if = \"Option::is_none\")]\n\
         \tpub payload: Option<serde_json::Value>,\n\
         \t#[serde(skip_serializing_if = \"Option::is_none\")]\n\
         \tpub code: Option<String>,\n\
         \t#[serde(skip_serializing_if = \"Option::is_none\")]\n\
         \tpub retryable: Option<bool>,\n\
         }\n\n\
         #[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
         pub struct CommandContract {\n\
         \tpub public_method: &'static str,\n\
         \tpub wire_name: &'static str,\n\
         \tpub category: &'static str,\n\
         \tpub durable: bool,\n\
         \tpub requires_command_id: bool,\n\
         \tpub idempotent: bool,\n\
         \tpub handler_key: &'static str,\n\
         }\n\n",
    );
    output.push_str(&format!("pub const PROTOCOL: u16 = {};\n\n", manifest.protocol));
    output.push_str("pub const COMMANDS: &[CommandContract] = &[\n");
    for command in &manifest.commands {
        output.push_str(&format!(
            "    CommandContract {{ public_method: {:?}, wire_name: {:?}, category: {:?}, durable: {}, requires_command_id: {}, idempotent: {}, handler_key: {:?} }},\n",
            command.public_method,
            command.wire_name,
            command.category,
            command.durable,
            command.requires_command_id,
            command.idempotent,
            command.handler_key,
        ));
    }
    output.push_str(
        "];\n\n\
         pub fn command_contract(wire_name: &str) -> Option<&'static CommandContract> {\n\
         \tCOMMANDS.iter().find(|command| command.wire_name == wire_name)\n\
         }\n",
    );
    output
}

fn render_dart(manifest: &Manifest) -> String {
    let mut output = String::from(HEADER);
    output.push_str(
        "final class GeneratedCommandRequest {\n\
         \tconst GeneratedCommandRequest({required this.type, this.commandId, this.payload = const <String, Object?>{}});\n\
         \tfinal String type;\n\
         \tfinal String? commandId;\n\
         \tfinal Map<String, Object?> payload;\n\
         \tMap<String, Object?> toJson() => <String, Object?>{\n\
         \t\t'type': type,\n\
         \t\tif (commandId != null) 'commandId': commandId,\n\
         \t\t'payload': payload,\n\
         \t};\n\
         }\n\n\
         final class GeneratedCommandResponse {\n\
         \tconst GeneratedCommandResponse({required this.status, this.payload, this.code, this.retryable});\n\
         \tfinal String status;\n\
         \tfinal Object? payload;\n\
         \tfinal String? code;\n\
         \tfinal bool? retryable;\n\
         \tfactory GeneratedCommandResponse.fromJson(Map<String, Object?> json) => GeneratedCommandResponse(\n\
         \t\tstatus: json['status'] as String,\n\
         \t\tpayload: json['payload'],\n\
         \t\tcode: json['code'] as String?,\n\
         \t\tretryable: json['retryable'] as bool?,\n\
         \t);\n\
         }\n\n\
         final class GeneratedCommandContract {\n\
         \tconst GeneratedCommandContract({\n\
         \t\trequired this.publicMethod,\n\
         \t\trequired this.wireName,\n\
         \t\trequired this.category,\n\
         \t\trequired this.durable,\n\
         \t\trequired this.requiresCommandId,\n\
         \t\trequired this.idempotent,\n\
         \t\trequired this.handlerKey,\n\
         \t});\n\
         \tfinal String publicMethod;\n\
         \tfinal String wireName;\n\
         \tfinal String category;\n\
         \tfinal bool durable;\n\
         \tfinal bool requiresCommandId;\n\
         \tfinal bool idempotent;\n\
         \tfinal String handlerKey;\n\
         }\n\n",
    );
    output.push_str(&format!("const generatedProtocol = {};\n\n", manifest.protocol));
    output.push_str("const generatedCommands = <GeneratedCommandContract>[\n");
    for command in &manifest.commands {
        output.push_str(&format!(
            "  GeneratedCommandContract(publicMethod: {:?}, wireName: {:?}, category: {:?}, durable: {}, requiresCommandId: {}, idempotent: {}, handlerKey: {:?}),\n",
            command.public_method,
            command.wire_name,
            command.category,
            command.durable,
            command.requires_command_id,
            command.idempotent,
            command.handler_key,
        ));
    }
    output.push_str(
        "];\n\n\
         final generatedCommandByWireName = <String, GeneratedCommandContract>{\n\
         \tfor (final command in generatedCommands) command.wireName: command,\n\
         };\n",
    );
    output
}

fn render_kotlin(manifest: &Manifest) -> String {
    let mut output = String::from(HEADER);
    output.push_str("package org.torchat.generated\n\n");
    output.push_str(
        "import org.json.JSONObject\n\n\
         data class GeneratedCommandRequest(\n\
         \tval type: String,\n\
         \tval commandId: String? = null,\n\
         \tval payload: JSONObject = JSONObject(),\n\
         )\n\n\
         data class GeneratedCommandResponse(\n\
         \tval status: String,\n\
         \tval payload: Any? = null,\n\
         \tval code: String? = null,\n\
         \tval retryable: Boolean? = null,\n\
         )\n\n\
         data class GeneratedCommandContract(\n\
         \tval publicMethod: String,\n\
         \tval wireName: String,\n\
         \tval category: String,\n\
         \tval durable: Boolean,\n\
         \tval requiresCommandId: Boolean,\n\
         \tval idempotent: Boolean,\n\
         \tval handlerKey: String,\n\
         )\n\n",
    );
    output.push_str("object GeneratedCommandContracts {\n");
    output.push_str(&format!("    const val PROTOCOL: Int = {}\n", manifest.protocol));
    output.push_str("    val all: List<GeneratedCommandContract> = listOf(\n");
    for command in &manifest.commands {
        output.push_str(&format!(
            "        GeneratedCommandContract({:?}, {:?}, {:?}, {}, {}, {}, {:?}),\n",
            command.public_method,
            command.wire_name,
            command.category,
            command.durable,
            command.requires_command_id,
            command.idempotent,
            command.handler_key,
        ));
    }
    output.push_str(
        "    )\n\
         \tval byWireName: Map<String, GeneratedCommandContract> = all.associateBy { it.wireName }\n\
         }\n",
    );
    output
}

fn find_repo_root(mut path: PathBuf) -> Result<PathBuf, String> {
    loop {
        if path.join("Cargo.toml").is_file()
            && path.join("common/client-engine-contract.json").is_file()
        {
            return Ok(path);
        }
        if !path.pop() {
            return Err("could not locate repository root".to_owned());
        }
    }
}

fn write(path: &Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| error.to_string())?;
    }
    fs::write(path, content).map_err(|error| error.to_string())
}
