import 'dart:convert';
import 'dart:ffi' as ffi;
import 'dart:io';
import 'package:flutter/foundation.dart';
import '../generated/torca_contract.dart';
import 'engine_gateway.dart';
import 'ffi_engine_gateway_v4.dart' as base;

typedef _Handle=ffi.Pointer<ffi.Void>;typedef _EngineNewNative=_Handle Function();typedef _EngineNewDart=_Handle Function();typedef _EngineDestroyNative=ffi.Void Function(_Handle);typedef _EngineDestroyDart=void Function(_Handle);typedef _AllocNative=ffi.Pointer<ffi.Uint8> Function(ffi.UintPtr);typedef _AllocDart=ffi.Pointer<ffi.Uint8> Function(int);typedef _FreeNative=ffi.Void Function(ffi.Pointer<ffi.Uint8>,ffi.UintPtr);typedef _FreeDart=void Function(ffi.Pointer<ffi.Uint8>,int);typedef _IdNative=ffi.Int32 Function(_Handle,ffi.Pointer<ffi.Uint8>,ffi.UintPtr);typedef _IdDart=int Function(_Handle,ffi.Pointer<ffi.Uint8>,int);typedef _TwoStringsNative=ffi.Int32 Function(_Handle,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Pointer<ffi.Uint8>,ffi.UintPtr);typedef _TwoStringsDart=int Function(_Handle,ffi.Pointer<ffi.Uint8>,int,ffi.Pointer<ffi.Uint8>,int);typedef _RetryMessageNative=ffi.Int32 Function(_Handle,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Int64);typedef _RetryMessageDart=int Function(_Handle,ffi.Pointer<ffi.Uint8>,int,int);
typedef _QueueMessageReplyNative=ffi.Int32 Function(_Handle,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Int64);typedef _QueueMessageReplyDart=int Function(_Handle,ffi.Pointer<ffi.Uint8>,int,ffi.Pointer<ffi.Uint8>,int,ffi.Pointer<ffi.Uint8>,int,ffi.Pointer<ffi.Uint8>,int,int);
typedef _QueueAttachmentNative=ffi.Int32 Function(_Handle,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Pointer<ffi.Uint8>,ffi.UintPtr,ffi.Uint64);typedef _QueueAttachmentDart=int Function(_Handle,ffi.Pointer<ffi.Uint8>,int,ffi.Pointer<ffi.Uint8>,int,ffi.Pointer<ffi.Uint8>,int,ffi.Pointer<ffi.Uint8>,int,ffi.Pointer<ffi.Uint8>,int,ffi.Pointer<ffi.Uint8>,int,int);typedef _RefreshNative=ffi.Int32 Function(_Handle);typedef _RefreshDart=int Function(_Handle);typedef _PtrNative=ffi.Pointer<ffi.Uint8> Function(_Handle);typedef _PtrDart=ffi.Pointer<ffi.Uint8> Function(_Handle);typedef _LenNative=ffi.UintPtr Function(_Handle);typedef _LenDart=int Function(_Handle);

class FfiEngineGateway implements EngineGateway{
 FfiEngineGateway._(this._base,this._bindings,this._handle){_base.snapshots.addListener(_baseChanged);}static FfiEngineGateway open({ffi.DynamicLibrary? library}){final lib=library??ffi.DynamicLibrary.open(_libraryName());final wrapped=base.FfiEngineGateway.open(library:lib);final bindings=_FinalBindings(lib);final handle=bindings.engineNew();if(handle==ffi.nullptr)throw StateError('native Torca process handle could not be acquired');return FfiEngineGateway._(wrapped,bindings,handle);}static String _libraryName(){if(Platform.isWindows)return'torca_bridge.dll';if(Platform.isAndroid||Platform.isLinux)return'libtorca_bridge.so';if(Platform.isMacOS||Platform.isIOS)return'libtorca_bridge.dylib';throw UnsupportedError('Torca native runtime is unsupported on this platform');}
 final base.FfiEngineGateway _base;final _FinalBindings _bindings;final _Handle _handle;final ValueNotifier<AppSnapshotDto> _snapshots=ValueNotifier(const AppSnapshotDto());bool _disposed=false;@override ValueListenable<AppSnapshotDto> get snapshots=>_snapshots;
 Future<BridgeResultDto> initialize()async{final result=await _base.initialize();if(result.ok)_refreshFullSnapshot();return result;}
 @override Future<BridgeResultDto> execute(BridgeCommandDto c)async{if(_disposed)return const BridgeResultDto(ok:false,kind:'error',error:'native engine gateway is disposed');if(c is RenameContactCommandDto)return _two(c.contactIdHex,c.displayName,_bindings.renameContact);if(c is BlockContactCommandDto)return _id(c.contactIdHex,_bindings.blockContact);if(c is UnblockContactCommandDto)return _id(c.contactIdHex,_bindings.unblockContact);if(c is RemoveContactCommandDto)return _id(c.contactIdHex,_bindings.removeContact);if(c is ClearConversationHistoryCommandDto)return _id(c.conversationIdHex,_bindings.clearConversationHistory);if(c is QueueMessageCommandDto&&c.replyToMessageId!=null)return _reply(c);if(c is RetryMessageCommandDto)return _retryMessage(c);if(c is QueueAttachmentCommandDto)return _queueAttachment(c);if(c is RetryAttachmentCommandDto)return _id(c.attachmentIdHex,_bindings.retryAttachment);if(c is CancelAttachmentCommandDto)return _id(c.attachmentIdHex,_bindings.cancelAttachment);if(c is ExportAttachmentCommandDto)return _two(c.attachmentIdHex,c.destinationPath,_bindings.exportAttachment);final r=await _base.execute(c);if(r.ok)_refreshFullSnapshot();return r;}
 @override Future<String> diagnosticsJson()=>_base.diagnosticsJson();
 Future<BridgeResultDto> _two(String a,String b,_TwoStringsDart call)async{final x=_Utf8(_bindings,a),y=_Utf8(_bindings,b);try{call(_handle,x.pointer,x.length,y.pointer,y.length);}finally{x.dispose();y.dispose();}return _readAndRefresh();}
 Future<BridgeResultDto> _retryMessage(RetryMessageCommandDto c)async{final v=_Utf8(_bindings,c.messageIdHex);try{_bindings.retryMessage(_handle,v.pointer,v.length,c.atMs);}finally{v.dispose();}return _readAndRefresh();}
 Future<BridgeResultDto> _reply(QueueMessageCommandDto c)async{final r=c.replyToMessageId;if(r==null||r.isEmpty)return const BridgeResultDto(ok:false,kind:'error',error:'reply message id is required');final m=_Utf8(_bindings,c.messageIdHex),cv=_Utf8(_bindings,c.conversationIdHex),b=_Utf8(_bindings,c.body),q=_Utf8(_bindings,r);try{_bindings.queueMessageReply(_handle,m.pointer,m.length,cv.pointer,cv.length,b.pointer,b.length,q.pointer,q.length,c.atMs);}finally{m.dispose();cv.dispose();b.dispose();q.dispose();}return _readAndRefresh();}
 Future<BridgeResultDto> _queueAttachment(QueueAttachmentCommandDto c)async{final a=_Utf8(_bindings,c.attachmentIdHex),m=_Utf8(_bindings,c.messageIdHex),v=_Utf8(_bindings,c.conversationIdHex),p=_Utf8(_bindings,c.sourcePath),n=_Utf8(_bindings,c.name),t=_Utf8(_bindings,c.mediaType);try{_bindings.queueAttachment(_handle,a.pointer,a.length,m.pointer,m.length,v.pointer,v.length,p.pointer,p.length,n.pointer,n.length,t.pointer,t.length,c.size);}finally{a.dispose();m.dispose();v.dispose();p.dispose();n.dispose();t.dispose();}return _readAndRefresh();}
 Future<BridgeResultDto> _id(String id,_IdDart call)async{final v=_Utf8(_bindings,id);try{call(_handle,v.pointer,v.length);}finally{v.dispose();}return _readAndRefresh();}Future<BridgeResultDto> _readAndRefresh()async{final r=_result();if(r.ok)_refreshFullSnapshot();return r;}void _baseChanged(){if(!_disposed)_refreshFullSnapshot();}
 void _refreshFullSnapshot(){if(_bindings.refreshSnapshot(_handle)!=0)return;final raw=_read(_bindings.snapshotPointer(_handle),_bindings.snapshotLength(_handle));if(raw.isEmpty)return;_snapshots.value=_decodeSnapshot(raw);}BridgeResultDto _result(){final map=_map(jsonDecode(_read(_bindings.resultPointer(_handle),_bindings.resultLength(_handle))));return BridgeResultDto(ok:map['ok']==true,kind:map['kind']as String? ??'error',error:map['error']as String?);}
 AppSnapshotDto _decodeSnapshot(String raw){final map=_map(jsonDecode(raw));if(map['contractVersion']!=torcaContractVersion)throw const FormatException('native contract mismatch');final im=map['identity']==null?null:_map(map['identity']);return AppSnapshotDto(identity:im==null?null:IdentityDto(displayName:im['displayName']as String),torState:map['torState']as String? ??'stopped',onionAddress:map['onionAddress']as String?,pairings:_items(map['pairings']).map((v){final i=_map(v);return PairingDto(id:i['id']as String,code:i['code']as String,role:i['role']as String,state:i['state']as String,expiresAtMs:i['expiresAtMs']as int,localApproved:i['localApproved']as bool,remoteApproved:i['remoteApproved']as bool);}).toList(growable:false),contacts:_items(map['contacts']).map((v){final i=_map(v);return ContactDto(id:i['id']as String,displayName:i['displayName']as String,onionAddress:i['onionAddress']as String,status:i['status']as String,connectionState:i['connectionState']as String,safetyNumber:i['safetyNumber']as String?);}).toList(growable:false),conversations:_items(map['conversations']).map((v){final i=_map(v);return ConversationDto(id:i['id']as String,contactId:i['contactId']as String,status:i['status']as String);}).toList(growable:false),messages:_items(map['messages']).map((v){final i=_map(v);return MessageDto(id:i['id']as String,conversationId:i['conversationId']as String,body:i['body']as String,direction:i['direction']as String,status:i['status']as String,replyToMessageId:i['replyToMessageId']as String?,createdAtMs:i['createdAtMs']as int? ??0,updatedAtMs:i['updatedAtMs']as int? ??0,attemptCount:i['attemptCount']as int? ??0);}).toList(growable:false),attachments:_items(map['attachments']).map((v){final i=_map(v);return AttachmentDto(id:i['id']as String,messageId:i['messageId']as String,name:i['name']as String,mediaType:i['mediaType']as String,size:i['size']as int,status:i['status']as String,offset:i['offset']as int);}).toList(growable:false));}
 String _read(ffi.Pointer<ffi.Uint8> p,int l){if(p==ffi.nullptr||l==0)return'';return utf8.decode(p.asTypedList(l),allowMalformed:false);}Map<String,Object?> _map(Object? v)=>(v as Map).map((k,v)=>MapEntry(k.toString(),v));List<Object?> _items(Object? v)=>v is List?v.cast<Object?>():const[];
 @override Future<void> dispose()async{if(_disposed)return;_disposed=true;_base.snapshots.removeListener(_baseChanged);await _base.dispose();_bindings.engineDestroy(_handle);_snapshots.dispose();}
}
class _Utf8{_Utf8(this.bindings,String value):bytes=utf8.encode(value){pointer=bindings.alloc(bytes.length);if(bytes.isNotEmpty)pointer.asTypedList(bytes.length).setAll(0,bytes);}final _FinalBindings bindings;final List<int> bytes;late final ffi.Pointer<ffi.Uint8> pointer;int get length=>bytes.length;void dispose()=>bindings.free(pointer,bytes.length);}
class _FinalBindings{_FinalBindings(ffi.DynamicLibrary l):engineNew=l.lookupFunction<_EngineNewNative,_EngineNewDart>('torca_engine_new'),engineDestroy=l.lookupFunction<_EngineDestroyNative,_EngineDestroyDart>('torca_engine_destroy'),alloc=l.lookupFunction<_AllocNative,_AllocDart>('torca_alloc'),free=l.lookupFunction<_FreeNative,_FreeDart>('torca_free'),renameContact=l.lookupFunction<_TwoStringsNative,_TwoStringsDart>('torca_engine_rename_contact'),blockContact=l.lookupFunction<_IdNative,_IdDart>('torca_engine_block_contact'),unblockContact=l.lookupFunction<_IdNative,_IdDart>('torca_engine_unblock_contact'),removeContact=l.lookupFunction<_IdNative,_IdDart>('torca_engine_remove_contact'),clearConversationHistory=l.lookupFunction<_IdNative,_IdDart>('torca_engine_clear_conversation_history'),retryMessage=l.lookupFunction<_RetryMessageNative,_RetryMessageDart>('torca_engine_retry_message'),queueMessageReply=l.lookupFunction<_QueueMessageReplyNative,_QueueMessageReplyDart>('torca_engine_queue_message_reply'),queueAttachment=l.lookupFunction<_QueueAttachmentNative,_QueueAttachmentDart>('torca_engine_queue_attachment'),retryAttachment=l.lookupFunction<_IdNative,_IdDart>('torca_engine_retry_attachment'),cancelAttachment=l.lookupFunction<_IdNative,_IdDart>('torca_engine_cancel_attachment'),exportAttachment=l.lookupFunction<_TwoStringsNative,_TwoStringsDart>('torca_engine_export_attachment'),refreshSnapshot=l.lookupFunction<_RefreshNative,_RefreshDart>('torca_engine_refresh_snapshot'),resultPointer=l.lookupFunction<_PtrNative,_PtrDart>('torca_engine_result_ptr'),resultLength=l.lookupFunction<_LenNative,_LenDart>('torca_engine_result_len'),snapshotPointer=l.lookupFunction<_PtrNative,_PtrDart>('torca_engine_snapshot_ptr'),snapshotLength=l.lookupFunction<_LenNative,_LenDart>('torca_engine_snapshot_len');final _EngineNewDart engineNew;final _EngineDestroyDart engineDestroy;final _AllocDart alloc;final _FreeDart free;final _TwoStringsDart renameContact;final _IdDart blockContact,unblockContact,removeContact,clearConversationHistory;final _RetryMessageDart retryMessage;final _QueueMessageReplyDart queueMessageReply;final _QueueAttachmentDart queueAttachment;final _IdDart retryAttachment,cancelAttachment;final _TwoStringsDart exportAttachment;final _RefreshDart refreshSnapshot;final _PtrDart resultPointer,snapshotPointer;final _LenDart resultLength,snapshotLength;}
