package org.torchat.mobile

object RuntimeContract {
    const val TYPE = "type"

    const val BOOTSTRAP_RUNTIME = "bootstrapRuntime"
    const val REPORT_TOR_STATUS = "reportTorStatus"
    const val APPLY_REMOTE_PROFILE = "applyRemoteProfile"
    const val REPORT_RUNTIME_ERROR = "reportRuntimeError"
    const val REPORT_RUNTIME_LOG = "reportRuntimeLog"
    const val CONNECT = "connect"
    const val IDENTITY = "identity"
    const val PROFILE = "profile"
    const val SET_NICKNAME = "setNickname"
    const val REFRESH_PAIRING_CODE = "refreshPairingCode"
    const val PREPARE_SUBMIT_PAIRING_CODE = "prepareSubmitPairingCode"
    const val SUBMIT_PAIRING_CODE = "submitPairingCode"
    const val PAIRING_INBOX = "pairingInbox"
    const val MERGE_PAIRING_INBOX = "mergePairingInbox"
    const val PAIRING_OUTBOX = "pairingOutbox"
    const val MERGE_PAIRING_OUTBOX = "mergePairingOutbox"
    const val ACCEPT_PAIRING = "acceptPairing"
    const val REJECT_PAIRING = "rejectPairing"
    const val CANCEL_PAIRING = "cancelPairing"
    const val PREPARE_ACCEPT_PAIRING = "prepareAcceptPairing"
    const val COMMIT_ACCEPT_PAIRING = "commitAcceptPairing"
    const val BOOTSTRAP_CONTACT = "bootstrapContact"
    const val PREPARE_REJECT_PAIRING = "prepareRejectPairing"
    const val COMMIT_REJECT_PAIRING = "commitRejectPairing"
    const val ARCHIVE_PAIRING = "archivePairing"
    const val PREPARE_CANCEL_PAIRING = "prepareCancelPairing"
    const val CONFIRM_PAIRING_CANCELLED = "confirmPairingCancelled"
    const val PREPARE_PENDING_SEND_EFFECTS = "preparePendingSendEffects"
    const val APPLY_PAIRING_PEER_OUTCOME = "applyPairingPeerOutcome"
    const val WELCOME_ACCEPTED = "welcomeAccepted"
    const val VERIFY_CONTACT = "verifyContact"
    const val CONTACTS = "contacts"
    const val CONVERSATIONS = "conversations"
    const val MESSAGES = "messages"
    const val OPEN_CONVERSATION = "openConversation"
    const val CLOSE_CONVERSATION = "closeConversation"
    const val START_CONVERSATION = "startConversation"
    const val SEND_MESSAGE = "sendMessage"
    const val RECEIVE_MESSAGE = "receiveMessage"
    const val APPLY_MESSAGE_TRANSPORT_OUTCOME = "applyMessageTransportOutcome"
    const val OUTCOME_FORWARDED = "FORWARDED"
    const val OUTCOME_DELIVERED = "DELIVERED"
    const val OUTCOME_RECIPIENT_OFFLINE = "RECIPIENT_OFFLINE"
    const val OUTCOME_RETRYABLE_FAILURE = "RETRYABLE_FAILURE"
    const val OUTCOME_PERMANENT_FAILURE = "PERMANENT_FAILURE"
    const val PAIRING_OUTCOME_OFFER_RECEIVED = "OFFER_RECEIVED"
    const val PAIRING_OUTCOME_REJECTION_RECEIVED = "REJECTION_RECEIVED"
    const val PAIRING_OUTCOME_WELCOME_PREPARED = "WELCOME_PREPARED"

    const val RUNTIME_READY = "runtime_ready"
    const val TOR_STATUS = "tor_status"
    const val PROFILE_READY = "profile_ready"
    const val INVITE_RECEIVED = "invite_received"
    const val INVITE_STATE_CHANGED = "invite_state_changed"
    const val MESSAGE_RECEIVED = "message_received"
    const val MESSAGE_STATE_CHANGED = "message_state_changed"
    const val CONVERSATION_READ_CHANGED = "conversation_read_changed"
    const val CHANGED = "changed"
    const val RUNTIME_ERROR = "runtime_error"
    const val RUNTIME_LOG = "runtime_log"
    const val NOTIFY_INCOMING = "notifyIncoming"
}
