[package]
name = "torca-platform-android"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
torca-platform = { path = "../torca-platform" }
torca-identity = { path = "../../domains/torca-identity" }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"

[lints]
workspace = true
