#!/usr/bin/env python3
"""Generate the client SQLite SQL catalog from files.

The generator is deterministic and intentionally contains no SQL parser. It
validates ownership, non-empty statements, unique logical names and emits only
`include_str!` constants. Domain logic remains in Rust repositories.
"""
from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

IDENT = re.compile(r"[^A-Za-z0-9]+")


@dataclass(frozen=True)
class Entry:
    section: str
    name: str
    relative_path: str


def identifier(value: str) -> str:
    result = IDENT.sub("_", value).strip("_").upper()
    if not result or result[0].isdigit():
        result = f"SQL_{result}"
    return result


def collect(sql_root: Path) -> list[Entry]:
    entries: list[Entry] = []
    seen: dict[tuple[str, str], Path] = {}
    for kind in ("queries", "commands"):
        root = sql_root / kind
        for path in sorted(root.rglob("*.sql")):
            text = path.read_text(encoding="utf-8")
            if not text.strip():
                raise ValueError(f"empty SQL file: {path}")
            relative = path.relative_to(sql_root).as_posix()
            parts = path.relative_to(root).parts
            section = identifier(parts[0] if len(parts) > 1 else kind)
            name = identifier("_".join(parts[1:] if len(parts) > 1 else parts).removesuffix(".SQL"))
            key = (section, name)
            if key in seen:
                raise ValueError(f"duplicate SQL catalog key {section}.{name}: {seen[key]} and {path}")
            seen[key] = path
            entries.append(Entry(section, name, relative))
    return entries


def render(entries: list[Entry]) -> str:
    by_section: dict[str, list[Entry]] = {}
    for entry in entries:
        by_section.setdefault(entry.section, []).append(entry)
    out = [
        "//! Generated by scripts/internal/generate_sql_catalog.py. Do not edit.\n",
        "//! Every query and command is a file-backed compile-time constant.\n\n",
    ]
    for section in sorted(by_section):
        out.append(f"pub(crate) mod {section.lower()} {{\n")
        for entry in sorted(by_section[section], key=lambda item: item.name):
            out.append(
                f'    pub(crate) const {entry.name}: &str = include_str!("../../../sql/{entry.relative_path}");\n'
            )
        out.append("}\n\n")
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("packages/torchat-storage/src/storage/sqlite/generated_sql_catalog.rs"),
    )
    args = parser.parse_args()
    root = args.root.resolve()
    sql_root = root / "packages/torchat-storage/sql"
    output = args.output if args.output.is_absolute() else root / args.output
    content = render(collect(sql_root))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8", newline="\n")
    print(f"[torca] generated {output.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
