name: torchat_mobile
description: "TorChat Flutter mobile client"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  torchat_flutter_ui:
    path: ../../../packages/torchat-flutter-ui
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.6.1
  pixelarticons: ^0.4.0
  shared_preferences: ^2.3.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.0
  file_picker: ^11.0.2
  image: ^4.9.1
  window_manager: ^0.5.2
  tray_manager: ^0.5.3
  launch_at_startup: ^0.5.1
  local_notifier: ^0.1.6
  path_provider: ^2.1.6
  cryptography: ^2.9.0
  flutter_secure_storage: ^10.3.1

  gal: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/audio/intro.mp3

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
    - family: PixelifySans
      fonts:
        - asset: assets/fonts/PixelifySans-Variable.ttf
