[package]
name = "torca-peer-link"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
torca-connectivity = { path = "../../application/torca-connectivity" }
torca-contacts = { path = "../../domains/torca-contacts" }
torca-crypto = { path = "../torca-crypto" }
torca-foundation = { path = "../../foundation/torca-foundation" }
torca-peer = { path = "../torca-peer" }
torca-peer-protocol = { path = "../../protocol/torca-peer-protocol" }
torca-transport-api = { path = "../../application/torca-transport-api" }

[lints]
workspace = true
